### ISSUE TITLE
Eventing Integration

### ISSUE THREAD

**Issue by lance** [knative/func#1108]
The `func` CLI should provide developers the ability to find, inspect and subscribe to event sources.

Initial feature track document: https://docs.google.com/document/d/1RvVVtEWhEH8LgJI5X9zYGbWIsRivAT1qOz9ADs4ZG_8/edit?usp=sharing

**Comment by zroubalik** [comment]
@nainaz no this is more for triggers and sources wiring together with function deployment.

**Comment by matzew** [comment]
Sub-set of the Eventing integrations for creating Triggers: https://github.com/knative/func/issues/1956

**Comment by lance** [comment]
@matzew @lkingland I think this can be closed now that it's done - closing
