### ISSUE TITLE
Consider sub-command for displaying logs

### ISSUE THREAD

**Issue by matejvasek** [knative/func#112]
Might be useful to have something like `stern` to show stdout of functions.

**Comment by matejvasek** [comment]
@lance @lkingland wdyt?

**Comment by lance** [comment]
Seems reasonable, but I wonder why `kn` hasn't included this for a regular `Service`.

**Comment by rhuss** [comment]
there is a  [`kn service log`](https://github.com/rhuss/kn-service-log) plugin in the making that works similar to stern. It's still on my private account but should move over to `knative-sandbox` soon.

We have to implement that as a plugin as showing the logs of a pod is not part of the Knative API contract.
