### ISSUE TITLE
IDE Plugin Exploration

### ISSUE THREAD

**Issue by lance** [knative/func#1126]
The Red Hat Developer organization currently has Knative support for both IntelliJ and VSCode. In the case of VSCode, function support is currently in an early release stage.

https://github.com/redhat-developer?q=knative

**Comment by mohitsuman** [comment]
We have implemented and released the developer workflow for serverless functions for Visual Studio Code and IntelliJ.

Here are the download links for the extension:

- Visual Studio Code: https://marketplace.visualstudio.com/items?itemName=redhat.vscode-knative
- IntelliJ: https://plugins.jetbrains.com/plugin/16476-knative-by-red-hat

The workflow currently supports the latest kn-func cli experience.

**Comment by lance** [comment]
On going work. @mohitsuman is there anything else you want to add here for an update?

**Comment by mohitsuman** [comment]
We have the latest version of the Serverless Functions extension now available on VSCode and IntelliJ. This extension supports latest func cli workflow, with all the features for 1.7.0.

VSCode: https://marketplace.visualstudio.com/items?itemName=redhat.vscode-knative
IntelliJ: https://plugins.jetbrains.com/plugin/16476-knative--serverless-functions-by-red-hat

We can now close this issue.

**Comment by mohitsuman** [comment]
yes we can close this issue as we have a working support on IDE. For specific issues we can track them separately.
