### ISSUE TITLE
 Add flag to pass the details for adding/removing the func config envs/volumes.

### ISSUE THREAD

**Issue by sudhirverma** [knative/func#1182]
Issue: https://github.com/redhat-developer/vscode-knative/issues/190

As required in VSCode we would need flags to add/remove configured environment variable and volumes.

for e.g:
```
func config envs add -type 'type of enviroment variable' -name 'name' -value 'value'

func config envs add -type 'type of enviroment variable'  -configMap 'configMap'
```

cc: @mohitsuman @lstocchi

**Comment by mohitsuman** [comment]
With the current implementation of `func cli` asking interactive prompts to the user, from the IDE side of things we would pass those prompts as dropdown options and once the user selects them, the command would be passed as a flag directly.
This way we can support multiple parameters (anything added in future) through the IDE workflow.

**Comment by matejvasek** [comment]
@sudhirverma 
How output of `func config envs list` should look like?
```
[{"Name":"abc","Value":"42"},{"Name":"cba","Value":"{{ env:HOME }}"}]
```

Or somehow else?

**Comment by matejvasek** [comment]
Also do we want specific flags for secrets/configMaps, or would we be content with just `--name` and `--value` (which would require `{{}}` for special values)?

**Comment by matejvasek** [comment]
cc @lance @zroubalik @lkingland

**Comment by sudhirverma** [comment]
> How output of `func config envs list` should look like?
> 
> ```
> [{"Name":"abc","Value":"42"},{"Name":"cba","Value":"{{ env:HOME }}"}]
> ```

this would be good to show output when we do `func config envs list -ojson or --json`.

**Comment by lance** [comment]
Let's identify in specifics what commands need what flags. I think it's a pretty big list

**For `func config envs add`**
* `--name` the name of the environment variable
* `--value` for hard coded variables - how should this work for variables from the environment? Do we just have the user enter the string `{{ env.MY_ENV }}` directly?
* `--configMap` for keys/values stored in a ConfigMap. If `--name` is provided, only a single value with key corresponding to `--name` is used. If `--name` is not provided, all key/value pairs are used.
* `--secret` behaving the same as `--configMap` above, but with secrets.

For `func config labels add` and `func config annotations add` I think we can eliminate the `--configMap` and `--secret` flags.

So, for example, a user wanting to add an environment variable named `FOO` with a value from the current environment `BAR` variable, they would type

```
func config envs add --name FOO --value "{{ env.BAR }}"
```

To use all values from the `ConfigMap` called myConfig.

```
func config envs add --configMap myConfig
```

We also need to add the `--name` flag to `func config [envs|labels|annotations] delete` command to delete a specific key/value pair.

Does this all sound about right?

**Comment by matejvasek** [comment]
@lance 
Yeah,  but instead of
```
func config envs add --configMap myConfig
````

we could have just
```
func config envs add --value '{{ configMap:myConfig  }}'
```
It would be simple to implement it that way, however user would have to know the expression language.
Basically there would be just `--name` and `--value` flags.

**Comment by lance** [comment]
> It would be simple to implement it that way, however user would have to know the expression language.

True - but also users can either use the interactive prompt or the IDE.

**Comment by lance** [comment]
@matejvasek can this be closed now given that https://github.com/knative-sandbox/kn-plugin-func/pull/1188 has landed?

**Comment by matejvasek** [comment]
Only adding and listing of envvars is implemented, deletion is not.
Also volumes are not implemented at all.

**Comment by lance** [comment]
> Only adding and listing of envvars is implemented, deletion is not. Also volumes are not implemented at all.

Ok thanks for the update. Do you think it would help to break this into a couple of different issues? Now that adding/listing env vars is in place it might be easier for someone to pick up additional pieces.

**Comment by lance** [comment]
Moving this to "Next" instead of "In progress" since some of it did get done but not all of it.
