### ISSUE TITLE
Create automation for updating spring boot dependencies

### ISSUE THREAD

**Issue by salaboy** [knative/func#1190]
Following the quarkus approach: https://github.com/knative-sandbox/kn-plugin-func/blob/main/hack/update-quarkus-platform.js 

We should have a similar automation for Spring Boot dependencies. Tasks: 
- [ ] Find out how to query for latest version on http://start.spring.io
- [ ] copy quarkus script and adapt
- [ ] Make sure that the automation script is executed when the quarkus plugin is executed (@matejvasek can you provide some pointers about the lifecycle of the `update-quarkus-platform.js` file? who is in charge of running that?

**Comment by ningyan325** [comment]
Anyone working on this? For getting the latest version of sprint boot, this api seem does it (https://api.github.com/repos/spring-projects/spring-boot/releases/latest)... Otherwise I'd like to contribute and having someone assign this to me?

**Comment by zroubalik** [comment]
@ningyan325 awesome, please go ahead with it.
