### ISSUE TITLE
Add support for named branches in `func repository add` command

### ISSUE THREAD

**Issue by lance** [knative/func#1197]
Currently, the `func repository add` command will only work for github repositories that are on the main branch and there is no way to specify an alternate. It would be nice to have `func repository add --branch <branch-name> <name> <url>`.

/kind enhancement
/kind good-first-issue

**Comment by daisy-ycguo** [comment]
I will try it.
/assign

**Comment by grafvonb** [comment]
Hi @daisy-ycguo, are you working on that?

**Comment by daisy-ycguo** [comment]
> Hi @daisy-ycguo, are you working on that?

Yes, just got some time and pick up this work.
