### ISSUE TITLE
REST Methods

### ISSUE THREAD

**Issue by obikay200** [knative/func#1242]
Currently looking at the templates, only the GET and POST methods are supported.

What is the road map for adding the remainder of the http methods such as DELETE etc?

Thanks

**Comment by salaboy** [comment]
@obikay200 what language templates are you looking at? You can always create a function without using the base templates and then you can map any endpoint that you want for your function. The go template for example is using a base layer that adds this initial mappings, but there is nothing that force you to use that.

**Comment by lkingland** [comment]
@obikay200 all of the request methods are supported.  The included templates are merely examples.  Functions should not obscure access to the raw http requests in any of the languages.... that I am aware of.  Closing this.  Please re-open an issue if this is not true or you need more information, especially noting the language templates you're looking at

**Comment by lance** [comment]
> Functions should not obscure access to the raw http requests in any of the languages

@salaboy @lkingland - Honestly, I think this might be dependent on the invocation framework. For example, I'm pretty sure Quarkus does not out of the box (could be mistaken), and I'm almost certain that faas-js-runtime only supports GET and POST at the moment. If we do want to support all HTTP verbs, we should call that out - perhaps in a larger epic that applies to all builtin runtimes.
