### ISSUE TITLE
Improve test coverage for 1.8 release

### ISSUE THREAD

**Issue by salaboy** [knative/func#1275]
This is a planning issue to organize the work around unit testing.

Looking at codecov (you need to be logged in to see the coverage details per file): https://app.codecov.io/gh/knative-sandbox/kn-plugin-func/tree/main/ these are the different directories where we should try to increase (or add coverage)  in these directories to make an impact: 

- [x] #1278
- [x] k8s: https://app.codecov.io/gh/knative/func/tree/main/k8s (close to 8%)
- [ ] buildpacks: https://app.codecov.io/gh/knative/func/tree/main/buildpacks (close to 36%)
- [ ] pipelines: https://app.codecov.io/gh/knative/func/tree/main/pipelines/tekton (close to 36%)

We can create separate issues to track each of these directories

**Comment by lance** [comment]
Including integration tests in our code coverage reports now puts the `k8s` package at > %56

**Comment by mcruzdev** [comment]
Hi @lance, can you assign it for me?

**Comment by lance** [comment]
- `knative` package now at > 63%
- `k8s` package now at > 63%
- `buildpacks` package now at > 55%
- `pipelines` package now at 38%

We did not hit the target for pipelines, however our overall coverage is now at approximately 63%. I'm going to close this for now, and if we want to set an explicit target for either overall or low-coverage `pipelines` in `release-1.9` let's open new issues.

/close
