### ISSUE TITLE
Improve coverage of knative package (currently close to 6%)

### ISSUE THREAD

**Issue by salaboy** [knative/func#1278]
See: https://app.codecov.io/gh/knative-sandbox/kn-plugin-func/tree/main/knative

**Comment by salaboy** [comment]
@lance @zroubalik @lkingland can we merge this one now?

**Comment by gabo1208** [comment]
Now this should be the codecov chore link https://app.codecov.io/gh/knative/func

**Comment by lance** [comment]
@salaboy we are now at 64% test coverage on the knative package. This puts us well into the "Usable" state as defined here: https://github.com/knative/community/pull/1157

I think we want to continue improving this to get to "Stable" (70%) but for the purposes of this issue, I think we can close it now and if we have a specific target (like 70%) we can create a new issue for that. It might be good, actually to have an Epic similar to the [on-cluster build epic](https://github.com/knative/func/issues/620), with subtasks to track specific goals for specific packages.

Feel free to reopen this if you disagree and would like to discuss.
