### ISSUE TITLE
Minimal initial func.yaml

### ISSUE THREAD

**Issue by lkingland** [knative/func#1279]
## Summary

All fields on the `Function` struct should be set to `omitempty`

## Exposition

When a user creates a new Function, their `func.yaml` should include only the values which are either required (language), have no default (created date/time stamp) or deviate from static defaults (`func create -l go -t cl.

With the current version of the functions core library, this would _ideally_ look as such:
```shell
>  mkdir f && cd f && func create -l go
Created go function in [path]

> cat func.yaml
specVersion: 0.25.0
runtime: go
created: 2022-09-26T23:06:48.442316+09:00
```

## Alternative Considered: The fully-populated Config File approach
 
A traditional "config file" style setup would be where the func.yaml is fully populated with all possible values (commented and showcasing static defaults), whereby the user can choose to uncomment a given setting.  However, this usage pattern is directly at odds with the usage pattern we are encouraging: CLI or direct API.  For example, we using our friend `git` as an example, only when configuration is changed using `git config ...` does the `.git/config` file change.  This is the opposite approach to, for example `sshd`, which upon installation provides a comprehensive config file available at `/etc/ssh/sshd_config`.  The reason for the difference is that the former has a CLI which provides for configuration, while the latter does not.  We have a CLI.

This is of course up for debate.  It might be nice to account for a user who prefers  a `func.yaml`-first approach.  That may very well happen in the future, but this minimal approach should probably still be the first step.  We currently have the worst of both worlds, were func.yaml is populated with an intimidating litany of uncommented zero values.

## Caviat: It won't be that simple right now

Even if all fields are set to `omitempty`, the func.yaml will still include several more values.  This is a result of having not been strict in our usage of in-code static defaults early on, and requiring a few values we don't really need, so there are still a few fields which are written to every func.yaml despite not being actually deviations from the default.  The closest we can get _at present_ would be:

```
specVersion: 0.25.0
name: f
runtime: go
healthEndpoints:
  liveness: /health/liveness
  readiness: /health/readiness
buildpacks:
- paketo-buildpacks/go-dist
- ghcr.io/boson-project/go-function-buildpack:tip
created: 2022-09-26T23:06:48.442316+09:00
invocation:
  format: http
```

## Related

See forthcoming issues which request that we rely on the static defaults for buildpacks and health endpoints, only require a name upon deploy, and flatten the `invocation` struct (also relying on `http` as the static default)

**Comment by lkingland** [comment]
That's great @manoelmarques .  It might be good to perform the `omitempty` change in in one PR and do the default buildpacks in another:

If I remember correctly, the buildpack defaults should be static defaults in the pack builder `builders/buildpacks/builder.go`.  Buildpacks specified in func.yaml (or a custom template) would become overrides. So if empty, the defaults in the `buildpacks.Builder` would take effect on build.  

That means that, in the default case, the func.yaml would have no buildpacks specified. 

I say the change to update to using in-code defaults maybe should be a separate PR because the buildpacks builder might need to be appreciably modified.

**Comment by manoelmarques** [comment]
Hi @lkingland I added the flag and created a PR. However, during the CI, there were two errors when deploying to cluster. One caused by the `Image` and the other `Registry`. I removed the `omitempty` from those two and it all worked. Currently the PR passes CI. The errors are below:

Image:
```
=== RUN   TestBasicUpload
    cmd.go:83: /home/runner/work/func/func/func create -l node /tmp/TestBasicUpload3227201013/001/test-func-basic-upload29khr
    cmd.go:83: /home/runner/work/func/func/func deploy -p /tmp/TestBasicUpload3227201013/001/test-func-basic-upload29khr -r ttl.sh/knfunc2pqk62fp --remote --verbose
    cmd.go:127: Creating Pipeline resources
        Running Pipeline Task: Building function image on the cluster
        Running Pipeline Task: Deploying function to the cluster
        Error: failed to run pipeline: function pipeline run has failed with message: 
        
        ⬆️  Deploying function to the cluster
        deploy error: knative deployer failed to deploy the Knative Service: admission webhook "validation.webhook.serving.knative.dev" denied the request: validation failed: missing field(s): spec.template.spec.containers[0].image
        Error: knative deployer failed to deploy the Knative Service: admission webhook "validation.webhook.serving.knative.dev" denied the request: validation failed: missing field(s): spec.template.spec.containers[0].image
        
        
    cmd.go:128: exit status 1
    cmd.go:83: /home/runner/work/func/func/func invoke -p /tmp/TestBasicUpload3227201013/001/test-func-basic-upload29khr
    cmd.go:127: Error: services.serving.knative.dev "test-func-basic-upload29khr" not found
        
    cmd.go:128: exit status 1
    scenario_basic_test.go:41: assertion failed: expression is false: strings.Contains(result.Out, "first revision"): Func body does not contain 'first revision'
    cmd.go:83: /home/runner/work/func/func/func delete -p /tmp/TestBasicUpload3227201013/001/test-func-basic-upload29khr
    cmd.go:127: 
        
   Removing Knative Service: test-func-basic-upload29khr
        
   Removing Knative Service 'test-func-basic-upload29khr' and all dependent resources
        Error: knative remover failed to delete the service: services.serving.knative.dev "test-func-basic-upload29khr" not found
        
    cmd.go:128: exit status 1
--- FAIL: TestBasicUpload (76.11s)
```
Registry, after removing `omitempty` from Image:
```
=== RUN   TestBasicGit
    gitserver.go:83: Initialized HTTP Func Git Server: Server URL = http://func-git.default.127.0.0.1.sslip.io/ Pod Name = func-git-00001-deployment-69ff558-r54wv
    cmd.go:83: kubectl exec func-git-00001-deployment-69ff558-r54wv -c user-container -- git-repo create test-func-basic-gitctx2s
    cmd.go:122: Initialized empty Git repository in /var/www/git/test-func-basic-gitctx2s.git/
        created
    cmd.go:83: /home/runner/work/func/func/func create -l node /tmp/TestBasicGit4213784320/001/test-func-basic-gitctx2s
    cmd.go:83: sh -c git init
    cmd.go:83: sh -c git branch -M main
    cmd.go:83: sh -c git add .
    cmd.go:83: sh -c git config user.name "John Smith"
    cmd.go:83: sh -c git config user.email "john.smith@example.com"
    cmd.go:83: sh -c git commit -m "initial commit"
    cmd.go:83: sh -c git remote add origin http://func-git.default.127.0.0.1.sslip.io/test-func-basic-gitctx2s.git
    cmd.go:83: sh -c git push -u origin main
    cmd.go:83: /home/runner/work/func/func/func deploy -p /tmp/TestBasicGit4213784320/001/test-func-basic-gitctx2s -r ttl.sh/knfuncmhujvp0s --remote --verbose --git-url http://func-git.default.svc.cluster.local/test-func-basic-gitctx2s.git
    cmd.go:127: Creating Pipeline resources
        Running Pipeline Task: Fetching git repository with the function source code
        Running Pipeline Task: Building function image on the cluster
        Running Pipeline Task: Deploying function to the cluster
        Error: failed to run pipeline: function pipeline run has failed with message: 
        
        Warning: function has current image 'ttl.sh/knfuncmhujvp0s/test-func-basic-gitctx2s:latest' which has a different registry than the currently configured registry 'image-registry.openshift-image-registry.svc:5000/default'. The new image tag will be 'image-registry.openshift-image-registry.svc:5000/default/test-func-basic-gitctx2s:latest'.  To use an explicit image, use --image.
        ⬆️  Deploying function to the cluster
        Waiting for Knative Service to become ready
        deploy error: knative deployer failed to wait for the Knative Service to become ready: RevisionFailed: Revision "test-func-basic-gitctx2s-00001" failed with message: Unable to fetch image "image-registry.openshift-image-registry.svc:5000/default/test-func-basic-gitctx2s:latest": failed to resolve image to digest: Get "https://image-registry.openshift-image-registry.svc:5000/v2/": dial tcp: lookup image-registry.openshift-image-registry.svc on 10.96.0.10:53: no such host.
        Error: knative deployer failed to wait for the Knative Service to become ready: RevisionFailed: Revision "test-func-basic-gitctx2s-00001" failed with message: Unable to fetch image "image-registry.openshift-image-registry.svc:5000/default/test-func-basic-gitctx2s:latest": failed to resolve image to digest: Get "https://image-registry.openshift-image-registry.svc:5000/v2/": dial tcp: lookup image-registry.openshift-image-registry.svc on 10.96.0.10:53: no such host.
        
        
    cmd.go:128: exit status 1
    cmd.go:83: /home/runner/work/func/func/func invoke -p /tmp/TestBasicGit4213784320/001/test-func-basic-gitctx2s
    cmd.go:127: Error: failure invoking 'http://test-func-basic-gitctx2s.default.127.0.0.1.sslip.io/' (HTTP 404)
        
    cmd.go:128: exit status 1
    scenario_basic_test.go:99: assertion failed: expression is false: strings.Contains(result.Out, "first revision"): Func body does not contain 'first revision'
    cmd.go:83: /home/runner/work/func/func/func delete -p /tmp/TestBasicGit4213784320/001/test-func-basic-gitctx2s
    cmd.go:83: kubectl exec func-git-00001-deployment-69ff558-r54wv -c user-container -- git-repo delete test-func-basic-gitctx2s
    cmd.go:122: deleted
--- FAIL: TestBasicGit (55.92s)
```

**Comment by lkingland** [comment]
I am happy with this being an "as many as we can" thing.
if you have time, please open an issue noting that for some reason these fields are required to exist (they should not be) for Image and Registry, and we can proceed with removing as many as possible 👍🏻
