### ISSUE TITLE
Offer Function Logs via an HTTP request

### ISSUE THREAD

**Issue by lkingland** [knative/func#1309]
Any chance the function could provide a link to its own logs somehow on a GET? Probably not, but I thought it might be worth asking...

_Originally posted by @evankanderson in https://github.com/knative/docs/pull/5243#discussion_r989380651_

Perhaps provide a special (authenticated) endpoint on all Functions `https://<function route>/f/logs` which, when requested, streams logs to the client until the connection is closed.

**Comment by evankanderson** [comment]
I was suggesting this particularly for the getting started tutorial. I'm not sure what we might want to do for general-purpose functions.

For example, would we want to serve either automated (Open API?) or human-readable (html?) docs on a well-known endpoint? I don't know...

**Comment by Sanket-0510** [comment]
Hey if this feature of accessing the function logs via a HTTP request is still pending then I would like to give it a try. I am new to Knative in general but I do have idea regarding serverless and k8's. It would be better if someone here can provide me some extra context and flow regarding the issue.
