### ISSUE TITLE
FUNC_HOME environment variable

### ISSUE THREAD

**Issue by lkingland** [knative/func#1320]
For several reasons, we need an environment variable specifically for func home named FUNC_HOME, which will take the place of all calls to the function `ConfigPath()`.  It should exist only in the CLI, in order to provide a new optional constructor arguemt to the client, 'fn.WithHome(path string)`.  This value would be used internally to calculate such things as path to repositories, etc.  To accomplish this, we'll need to:

- Refactor Client to accept "config home" path as an optional functional option `fn.WithHome`, which will be used to calculate values such as `repositoriesPath`, which now relies directly on `fn.ConfigPath()`.  (Default of blank would indicate current working directory when not provided.).
- Move calcuation of ConfigPath (`func ConfigPath`) to the CLI and use it to provide a config path which first looks for FUNC_HOME, and if not provided, continues on to calculate the path using the current method (using XDG_CONFIG_HOME).
- Use this updated ConfigPath calculation to provide the home path in a `fn.WithHome(ConfigPath())` call in the shared client constructor in `client.go` such that all commands get it by default.
- Add/modify tests as appropriate 

Related: #1321

**Comment by lance** [comment]
@michelleyucollins that's great! I, however, am no longer working on this project. My colleague @lkingland is leading the effort now and should be able to work with you to make that happen. Thanks.

**Comment by lkingland** [comment]
Hello,

We would appreciate the contribution. 

/assign @michelleyucollins
