### ISSUE TITLE
docs rebuild encodes local environment

### ISSUE THREAD

**Issue by lkingland** [knative/func#1321]
Problem:
   When docs are regernerated, a user's current Function config path is used, leading to the docs potentially containing user settings.  For example, if repositories `functastic` and `knative` are installed in ~/.func/repositories, the resultant `docs/reference/func_create.md` would have the following in its diff after docs regeneration on `make`:
```diff
  --------     --------
	  go           cloudevents
	  go           http
+	  go           functastic/improve
+	  go           functastic/uppercase
+	  go           knative/improve
+	  go           knative/uppercase
...
```
Short-term Solution:
The same solution used in tests to avoid this should be workable here:  set `XDG_CONFIG_HOME` to an empty temp directory before docs generation, then set it back in a defer.

Longer-term Solution:
A possible longer term solution is to implement the (see [FUNC_HOME environment variable #1320](https://github.com/knative/func/issues/1320)), which will require a small refactor of Client.

**Comment by mcruzdev** [comment]
Hi @lance, can you assign it for me?

**Comment by lance** [comment]
/assign @mcruzdev 
Thanks for the offer!

**Comment by mcruzdev** [comment]
Hello @lkingland, how can I simulate it?

**Comment by mcruzdev** [comment]
Hi @lkingland, how can I simulate it?

Can you help me with step by step?

**Comment by lkingland** [comment]
@lance I can't seem to reproduce the problem on my system either. I remember it last happened with one of your rebuilds. Can you also confirm this is no longer happening? Perhaps we can close this issue as hopefully no longer being relevant

**Comment by lance** [comment]
@mcruzdev @lkingland this is odd - I can't reproduce this now either. Looking at the [generator history](https://github.com/knative/func/commits/main/docs/generator) there is nothing to indicate that this was somehow fixed. 

```
❯ func templates
LANGUAGE     TEMPLATE
go           cloudevents
go           http
go           knative/improve
go           knative/uppercase
node         cloudevents
node         http
nodejs       knative/metacontroller
python       cloudevents
python       http
python       knative/numpy
quarkus      cloudevents
quarkus      http
rust         cloudevents
rust         http
springboot   cloudevents
springboot   http
springboot   knative/uppercase
typescript   cloudevents
typescript   http

func on  main [$!] via 🐹 v1.19.1 on ☁️  lanceball@gmail.com
❯ make docs
# Generating command reference doc
go run docs/generator/main.go

func on  main [$!] via 🐹 v1.19.1 on ☁️  lanceball@gmail.com took 4s
❯ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   docs/reference/func_deploy.md

no changes added to commit (use "git add" and/or "git commit -a")
```

This one .md file diff is unrelated (it seems it never was applied from some other work being done on namespace, etc 👀 ).

**Comment by lkingland** [comment]
Great; I think this may have been alleviated with recent refactoring of the core library to disinclude evaluation of environment variables (pushing them out to main where they belog), and since your generator's main does not look for (nor care about) repositories on disk, this update is working as intended:  fixing seemingly unrelated errors.

**Comment by mcruzdev** [comment]
Perfect, thank you :)
