### ISSUE TITLE
Utilize .gitignore when sending source

### ISSUE THREAD

**Issue by lkingland** [knative/func#1322]
Thanks to PR #1298 we will now support the command `func deploy --remote` (without the previously-required `--git-url` flag).  This allows a user to build remotely using local source code.

A nice enhancement to this functionality would be to respect the local .gitignore if it exists, omitting files which match from the tarball streamed to the server for compilation.

In general, the tarball content should replicate a `git commit && git push && func deploy --remote --git-url=[repo]` as closely as possible... without the repo interstitial.

**Comment by grafvonb** [comment]
@lkingland I just analyzed the code base in the current `main` branch and this feature seems to be implemented by @matejvasek in `pipelines/tekton/pipeplines_provider.go` already last week:
```
func sourcesAsTarStream(f fn.Function) *io.PipeReader {
	ignored := func(p string) bool { return false }
	if gi, err := gitignore.CompileIgnoreFile(filepath.Join(f.Root, ".gitignore")); err == nil {
		ignored = func(p string) bool { return gi.MatchesPath(p) }
	}
[...]
```
Could you please check this? Thx.

**Comment by matejvasek** [comment]
Yes files in `.gitignore` should be already omitted #1298, however I forgot to exclude `.git/`.

**Comment by grafvonb** [comment]
@matejvasek ok, thanks for the info (nice code btw. 😎). So to omit `.git` we probably need a new ticket or update this one.

/unassign

**Comment by lkingland** [comment]
This is complete as of #1383
