### ISSUE TITLE
Better integration with Knative test and release infrastructure

### ISSUE THREAD

**Issue by lance** [knative/func#1333]
## Background

The Functions project was transferred to Knative from a small open source project from Red Hat known as Boson (https://github.com/boson-project). At that time, it did not make use of any Knative infrastructure. Over the months, we have slowly moved to adopt more and more of the tooling. And with our move from knative-sandbox to knative organization, we did even more. Now that we are on the path to GA for the Functions project we should fill in the remaining gaps.

I'm using the following as reference material.

- Creating a sandbox repository document: https://github.com/knative/community/blob/main/mechanics/CREATING-A-SANDBOX-REPO.md
- Knative `hack` repository README.md: https://github.com/knative/hack#readme
- Knative `test-infra` guides: https://github.com/knative/test-infra/tree/main/guides

## Current status

- [x] `LICENCE`, `OWNERS`, `CODE-OF-CONDUCT` and `README.md` in place
- [x] Peribolos configured for `func` repository
- [x] Golang knative.dev import redirects
- [x] Prow / testgrid setup
- [x] Peribolos configured for committers, leads, etc

## Remaining needs

After reviewing (while writing up this issue) it seems like we are __really__ close.

- [ ] Add a `hack/presubmit-tests.sh` script that sets up our CI, including a cluster with Knative Serving and Eventing, an in-cluster registry, and an in-cluster git server. We can pull the non-standard bits like the registry and git server from our existing `hack/` directory.
- [ ] Improve our testgrid/prow configuration to include continuous tests (for each commit to `main`). The dashboard for the client looks like this: https://testgrid.k8s.io/r/knative-own-testgrid/client#continuous and the configuration for that looks like this: https://github.com/knative/test-infra/blob/main/prow/jobs_config/knative/client.yaml
- [ ] Audit our existing CI for pull requests and commits to `main` and adjust where needed. I think using presubmit-tests for e2e tests and running them with Knative test infra will greatly simplify our `.github/workflows/ci.yaml`.
- [ ] Integrate with existing Knative image publishing

/cc @upodroid @kvmware 

/kind

**Comment by lkingland** [comment]
Closing as we are close enough with this integration to wait out the larger shift to using GitHub actions, where we have most of our work already
