### ISSUE TITLE
Provide a way to get template information.

### ISSUE THREAD

**Issue by sudhirverma** [knative/func#1366]
Fix: https://github.com/redhat-developer/vscode-knative/issues/295

Currently, we can’t know the template name of the created function. There should be a way to get template information after creating a function for `e:g: http | cloudevents | or other selected template`. 

The idea could be showing selected templated information in func.yaml

cc: @mohitsuman @lstocchi

**Comment by lstocchi** [comment]
I think you could use the invocation format field in func.yaml
```
invocation:
  format: http | cloudevent
```

**Comment by sudhirverma** [comment]
but if it is other than `http | cloudevent` it doesn’t show in  `invocation.format`

**Comment by matejvasek** [comment]
@lance @lkingland should we save template info in `func.yaml`?

**Comment by lkingland** [comment]
It's important to remember that the template used has very little bearing on what the function _can be_.

As long as your function adheres to the expected handler method signature, the template used is meaningless.

We encode the invocation format in func.yaml specifically as a hint to `func invoke` on how to format a test request.

I do not think we want to "pin" a function to its associated template, as this reduces the flexibility of the developer, who may want to start with one template and end up with something quite different.

**Comment by lkingland** [comment]
This information exists as the invocation method expected; aka the chosen method signature (see comment above)

**Comment by lkingland** [comment]
This information exists as the invocation method expected; aka the chosen method signature (see comment above)
