### ISSUE TITLE
Adding new template repositories throws error

### ISSUE THREAD

**Issue by andrew-su** [knative/func#1368]
# Problem
Attempting to add a new template repository fails with an error.

# Steps to repro
1. Create a template repo
1. Create a symlink
   * to a folder anywhere in the repo OR
   * to a non-existent file
1. Attempt to add the repo using func CLI
   ```
   func repo add foo https://github.com/andrew-su/kn-func-templates
   ```

# Error
```
➜  kn-func-templates git:(main) func repo add foo https://github.com/andrew-su/kn-func-templates
Error: failed to write repository: read /var/folders/3t/pgr00b9j4vz0fvlqdkct9cnm0000gp/T/func967622655/go/hello-world/foo: is a directory
```

**Comment by lkingland** [comment]
Thanks for the bug report.  I can recreate this on my system, and suspect it has to do with the underlying library we use for cloning repositories.

In the short term, you can:
```
cd ~/.config/func/repositories && git clone https://github.com/andrew-su/kn-func-templates foo
```

**Comment by andrew-su** [comment]
We worked around it by generating the symlinks at test time rather than checked into our repo for now.

**Comment by matejvasek** [comment]
>I can recreate this, and suspect it has to do with the underlying library we use for cloning repositories.

Nope, it's caused by inability of `copyFromFS()` to handle symlinks (especially symlinks to a directory).
I'll fix this.
