### ISSUE TITLE
YAML Schema in schemastore is outdated

### ISSUE THREAD

**Issue by trisberg** [knative/func#1398]
Creating function with v1.8.0 CLI creates a `func.yaml` with `specVersion: 0.34.0` which doesn't seem to match what is currently served from the schemastore - I think that is serving the older `0.25.0` version

**Comment by lance** [comment]
The `latest-release` branch has been updated to 1.8 (https://github.com/knative/func/tree/latest-release) and the schemastore has been updated: https://github.com/SchemaStore/schemastore/pull/2590. Note that VSCode should be using the `latest-release` branch so the referenced PR for schemastore is only a formality to add a named 1.8 schema.
