### ISSUE TITLE
ASP.NET Core language pack support

### ISSUE THREAD

**Issue by stevefan1999-personal** [knative/func#1408]
Ditto to title

**Comment by lance** [comment]
Hi @stevefan1999-personal thanks for opening this issue! Unfortunately, nobody that I am aware of on the team has .NET experience. We would, of course, be open to a pull request if you have any interest in working on this.

**Comment by clibequilibrium** [comment]
@stevefan1999-personal  feel free to check this https://github.com/knative/func/pull/1484
