### ISSUE TITLE
The func run command overwrites .gitignore

### ISSUE THREAD

**Issue by xonev** [knative/func#1420]
## Steps to reproduce
- Create a function using `func create` (e.g. `func create -l python myfunc`)
- Edit the `.gitignore` that is generated by `func create`
- Run `func run`

## Expected behavior
My changes to `.gitignore` are persisted

## Actual behavior
My changes to `.gitignore` are overwritten:
```
# Functions use the .func directory for local runtime data which should
# generally not be tracked in source control:
/.func
```

**Comment by xonev** [comment]
It looks like the problem is that `ensureRuntimeDir` is called during `Build`, as well: https://github.com/knative/func/blob/59f4e6a4935a97e0ea859602ad93bc49a0c58283/client.go#L545.

**Comment by lkingland** [comment]
Definitely a bug.  [this line](https://github.com/knative/func/blob/main/client.go#L573) should be an append not an overwrite.

**Comment by amaanq** [comment]
Apologies for the delay...just submitted a PR to fix this (although I didn't add a test per @lkingland 's suggestion, would be nice to have)

**Comment by lance** [comment]
Needs a test
