### ISSUE TITLE
Integration test enablement on Windows

### ISSUE THREAD

**Issue by matejvasek** [knative/func#1454]
Currently we are running integration tests only on Ubuntu in Github Actions.
We should run them also on Windows.

**Comment by ShlokMohanty** [comment]
@lance can we label this issue as testing framework ?

**Comment by lance** [comment]
@ShlokMohanty we don't use that label, but I think `techdebt` is appropriate.

/kind techdebt

**Comment by ShlokMohanty** [comment]
thank you @lance  for labeling it.
