### ISSUE TITLE
Better go module reflection of GOPATH

### ISSUE THREAD

**Issue by matzew** [knative/func#1459]
When creating a project, inside my `$GOPATH`, like:

```
func create -l go -t cloudevents      
Created go function in /home/matzew/go/src/github.com/matzew/payments
```

I was thinking that the `go.mod`, would reflect this a bit, and be like:

```golang
module github.com/matzew/payments

...
```

But instead it is a generic `function` module: https://github.com/knative/func/blob/main/templates/go/cloudevents/go.mod#L1

**Comment by lance** [comment]
@matzew this is an artifact of the way Go functions are currently constructed. The template files which comprise `main()` are currently part of the buildpack, and expect a module named `function`.

https://github.com/boson-project/packs/blob/e8e1b3b08ac5599c71e999a52a0ff4c0432baa29/buildpacks/go/faas/main.go#L19

In https://github.com/knative/func/pull/1451 I propose a path forward that removes this explicit dependency. (Also potentially in https://github.com/knative/community/issues/1220 which would extract most of what's in #1451 into a new repository).

**Comment by matzew** [comment]
Ugh, that's quiet some disadvantage, thanks for sharing
