### ISSUE TITLE
Go template dependencies are outdated

### ISSUE THREAD

**Issue by matzew** [knative/func#1460]
The go template uses some older dependencies, like:

* Golang 1.14
* Cloudevents SDK 2.5.0

See: https://github.com/knative/func/blob/main/templates/go/cloudevents/go.mod#L3-L5

Would it be reasonable to bump those to:

* Golang 1.18
* SDK 2.12

**Comment by lance** [comment]
@matzew let's see how this PR plays out https://github.com/knative/func/pull/1451

**Comment by ShlokMohanty** [comment]
@lance what's the update on this PR?

**Comment by ShlokMohanty** [comment]
if there is still a need for upgradation then we can label this issue as the good first issue?

**Comment by lance** [comment]
> if there is still a need for upgradation then we can label this issue as the good first issue?

@ShlokMohanty we are discussing some bigger changes to the Go templates in #1451 which would make this issue obsolete. I'd like to hold off for now on making any changes until we get the questions in 1451 resolved.

**Comment by ShlokMohanty** [comment]
@lance is the good first issue label removed from this issue ?

**Comment by lance** [comment]
> @lance is the good first issue label removed from this issue ?

Yes, mainly because these issues will likely be resolved in some form via #1451

**Comment by lkingland** [comment]
Related: #1469
