### ISSUE TITLE
Add support for .funcignore

### ISSUE THREAD

**Issue by lkingland** [knative/func#1463]
We were hoping to have a `.funcignore` file which would work much like `.gitignore` but for func-related tasks such as build (and especially `--remote` builds since this could be quite slow if the local directory contains a large amount of files!)

_Originally posted by @lkingland in https://github.com/knative/func/issues/1450#issuecomment-1334788575_

**Comment by lkingland** [comment]
Each of the two builder implementations, Pack and S2I, will need to be updated to respect a .funcignore file if it is present. This file should be of .gitignore format, and perhaps use github.com/sabhiram/go-gitignore since this library is already being used by the Pack builder internally. This library has a ComileIgnoreFile([path]) function which returns the .funcignore as a structure with a slice of IgnorePatterns, each of which has an actual regexp.Regex as its .Pattern member; making the next two steps straightforward:

In the Pack builder implementation, located in buildpacks/builder.go, each of the lines of the .funcignore will need to be added to the [pack builder's configuration](https://github.com/knative/func/blob/main/buildpacks/builder.go#L110) as an excludepack.BuildOptions.ProjectDescriptor.Build.Excludes

In the S2I builder implementation, located in s2i/builder.go, each of the lines of the .funcignore will need to be concatenated into a single large regex and set on the S2I builder's configuration as the single exclude regex api.Config.ExcludeRegExp

These each should have a test which uses a mock implementation for the builder to confirm that the .funcignore file was
correctly read and parsed into the expected string (no need to actually test if the files are excluded from the build, as this is the responsibility and an implementation detail of their requisite libraries). Ideally there would be a test confirming invalid .funcignore files properly fail fast as well.

**Comment by tydra-wang** [comment]
Anybody working on this? I am new to knative and would like to contribute. Can you assign this to me? @lance

**Comment by zroubalik** [comment]
@tydra-wang thanks!

**Comment by tydra-wang** [comment]
2 questions about the s2i builder implement for .funcignore.

> This library has a CompileIgnoreFile([path]) function which returns the .funcignore at path as a structure with a slice of IgnorePatterns, each of which has an actual regexp.Regex as its .Pattern member.

Using github.com/sabhiram/go-gitignore, I cannot get regexp patterns because the pattern slice is a private field of `CompileIgnoreFile` returned structure.

> In the S2I builder implementation, located in s2i/builder.go, each of the patterns from the .funcignore could be concatenated into a single large regex string and set on the [S2I builder's configuration](https://github.com/knative/func/blob/main/s2i/builder.go#L122) as the single exclude regex api.Config.ExcludeRegExp

.gitignore support negated pattern start with `!` and the latter rule could overwrite the previous. I doubt that we can simply convert a ignore file to a single regexp.


I am not familiar with s2i and I saw .s2iignore things in [s2i readme](https://github.com/openshift/source-to-image#build-workflow). Can we utilize this?

**Comment by lkingland** [comment]
Hello @tydra-wang 

Thank you for looking into this.

> Using github.com/sabhiram/go-gitignore, I cannot get regexp patterns because the pattern slice is a private field of CompileIgnoreFile returned structure.

I see that yes the`GitIgnore.patterns` member is indeed a private member.  However the `GitIgnore` object _does_ offer its own method that might be used instead: `GitIgnore.MatchesPath`?  Of course, using `go-gitignore` package is just a suggested shortcut so that we don't have to implement parsing of the `.funcignore` file ourselves.

> [due to negation patterns] I doubt that we can simply convert a ignore file to a single regexp

This very well might be true; thanks for looking into it!  Since we have to support a multitude of different builders, from Pack to S2I to potentially future builders, we will have to decide on a superset of features, and then do our best to implement them in the various builders.   For example, the docs you linked shows that providing a `.s2iignore` file when using s2i _does_ support the negations.  Perhaps we could simply pass the `.funcignore` file as the value for this option directly, or generate it if necessary!

Thanks again for looking into this more deeply.  Looking forward to what you come up with.

**Comment by tydra-wang** [comment]
The s2i builder copys source files filter by `api.Config.ExcludeRegExp` to a tmp directory, then remove files in tmp dir based on `.s2iignore`. 

@lkingland How about we just copy files filtered by .funcignore to a tmp dir and call builder using the tmp dir as source root?
Then we need not care about the details of builder implement.

**Comment by lkingland** [comment]
> The s2i builder copys source files filter by `api.Config.ExcludeRegExp` to a tmp directory, then remove files in tmp dir based on `.s2iignore`. 
> 
> 
> 
> @lkingland How about we just copy files filtered by .funcignore to a tmp dir and call builder using the tmp dir as source root?
> 
> Then we need not care about the details of builder implement.

That seems like it would work. Could we use links instead to avoid copying potentially large files?

**Comment by keshavcodex** [comment]
@tydra-wang are you still working on it?

**Comment by tydra-wang** [comment]
@keshavcodex Yes. I will open a pr in recent days.
