### ISSUE TITLE
Ensure Functions have Unfettered Access To their Requests and Responses

### ISSUE THREAD

**Issue by lkingland** [knative/func#1464]
> Functions should not obscure access to the raw http requests in any of the languages

@salaboy @lkingland - Honestly, I think this might be dependent on the invocation framework. For example, I'm pretty sure Quarkus does not out of the box (could be mistaken), and I'm almost certain that faas-js-runtime only supports GET and POST at the moment. If we do want to support all HTTP verbs, we should call that out - perhaps in a larger epic that applies to all builtin runtimes.

_Originally posted by @lance in https://github.com/knative/func/issues/1242#issuecomment-1286929900_

**Comment by lkingland** [comment]
This issue is such that we do not loose track of the goal that an instance of a function have direct access to the inbound HTTP request and outbound response or CloudEvent from the given language's standard library.

According to the referenced issue, this is the case for the Go function presentation code, but may not be the case for the other languages, so we should verify when time permits.

This expectation does not apply in the special situation where a template is very specifically intended to present a function as implementing a handler for a specific framework, but we should at least confirm that no request mangling or obfuscation is taking place in the situation of core language templates without framework middleware.

**Comment by lance** [comment]
Any requirements that we place on templates should be reflected in this document: https://github.com/knative/func/blob/main/docs/language-packs/language-pack-contract.md
