### ISSUE TITLE
Gorilla Mux is not longer maintained

### ISSUE THREAD

**Issue by salaboy** [knative/func#1469]
We might need to switch the use of `gorilla/mux` for another library that keeps getting maintained as Gorilla Mux is archived from the 9th December 2022:

https://github.com/gorilla/mux

@lance

**Comment by lance** [comment]
Yeah I saw this yesterday. I don't think a change is necessarily urgent, but we definitely should be considering it. This change should be applied in https://github.com/knative-sandbox/func-go. We may want to consider moving the issue there.

**Comment by mcruzdev** [comment]
Hi @salaboy, can you assign it for me?

**Comment by mcruzdev** [comment]
Hi @lance, I do not know if the correct pull request is this https://github.com/knative-sandbox/func-go/pull/3

**Comment by mcruzdev** [comment]
Hi @lance, I made the change on the boson-project/packs repo and close that pull request.

**Comment by matzew** [comment]
@mcruzdev I think the project is now having new maintainers

https://gorilla.github.io/blog/2023-07-17-project-status-update/
