### ISSUE TITLE
ImportError: cannot import name 'Context' from 'parliament' when running func.py directly

### ISSUE THREAD

**Issue by drriguz** [knative/func#1488]
Hi,
I'm following https://knative.dev/docs/getting-started/build-run-deploy-func and created a hello world function(python),
everything works perfectly, I can run the function by `kn func run`, however when execute the python script directly I get an error:

```
python test_func.py
Traceback (most recent call last):
  File "C:\Users\dr\Downloads\knative-test\helloworld\test_func.py", line 3, in <module>
    func = __import__("func")
  File "C:\Users\dr\Downloads\knative-test\helloworld\func.py", line 1, in <module>
    from parliament import Context
ImportError: cannot import name 'Context' from 'parliament' (C:\sdk\Python3.10\lib\site-packages\parliament\__init__.py)
```
Neither func.py nor test_func.py could be executed. I didnot found any description about running those python scripts directly, so is this supported?

Env:

* Windows 11 x64 + Docker desktop + minikube
* kn v1.8.1
* kn func v1.8.2

Thanks!

**Comment by jryberg** [comment]
@drriguz  You need to install parliament-functions using pip
```shell
pip install parliament-functions
```

I also installed "parliament" before I realized there are multiple projects with same name
