### ISSUE TITLE
Incorrect credentials to login to image registry (index.docker.io)

### ISSUE THREAD

**Issue by WindNotStop** [knative/func#1493]
In the case of confirming that the Username and Password are correct:
```
func deploy
Please provide credentials for image registry (index.docker.io).
? Username: xxxxxxxx
? Password: **************
Incorrect credentials, please try again.
```
I tried other versions of func cli as well but it doesn't work

**Comment by matejvasek** [comment]
@WindNotStop does it work with another registry (e.g. gcr ghcr or quay)?

**Comment by WindNotStop** [comment]
@matejvasek It works when I specify the parameter `--registry=docker.io/xxxxxxxx`
