### ISSUE TITLE
Cryptic error message: invalid builder ... try recreating builder

### ISSUE THREAD

**Issue by aslom** [knative/func#1505]
```
func run --build --verbose
Building function image
Pulling image gcr.io/paketo-buildpacks/builder:base
21335bec6bf5: Exists
5834a4dcd5e7: Exists
Error: invalid builder gcr.io/paketo-buildpacks/builder:base: builder gcr.io/paketo-buildpacks/builder:base missing label io.buildpacks.builder.metadata -- try recreating builder
```

**Comment by matejvasek** [comment]
>missing label io.buildpacks.builder.metadata 

That shouldn't be happening.

**Comment by matejvasek** [comment]
This looks like `gcr.io/paketo-buildpacks/builder:base` was temporary broken.

**Comment by aslom** [comment]
@matejvasek I am following tutorial https://knative.dev/docs/getting-started/build-run-deploy-func/ and have updated func CLI  to the latest version and recreated hello project. Still getting that error:

```
func version
v1.8.2

func create -l go hello
Created go function in /Users/aslom/Documents/awsm/go/src/github.com/aslom/hello

cd hello

export FUNC_REGISTRY=docker.io/aslom

func run -v
Building function image
Pulling image gcr.io/paketo-buildpacks/builder:base
21335bec6bf5: Exists
5834a4dcd5e7: Exists
Error: invalid builder gcr.io/paketo-buildpacks/builder:base: builder gcr.io/paketo-buildpacks/builder:base missing label io.buildpacks.builder.metadata -- try recreating builder
```

Anything else I could try to diagnose what is the problem?

**Comment by aslom** [comment]
Thanks with help from @matejvasek we verfied that there was actually no labels in the image:

```
docker image inspect gcr.io/paketo-buildpacks/builder@sha256:21335bec6bf590168906101a2102038a3257816541d7298e33f344de83057bf1 | jq '.[0].Config.Labels["io.buildpacks.builder.metadata"]'
null
```

And that was puzzling until I remembered that I have enabled "containerd integration Experimental Feature" in Docker  that “experimental containerd image store”.

After disabling it in Docker Desktop everythign worked :)

**Comment by matejvasek** [comment]
related to: https://github.com/moby/moby/issues/44646
