### ISSUE TITLE
Spinner "clock" icon should be removed when operation finishes

### ISSUE THREAD

**Issue by zroubalik** [knative/func#1513]
```
$ func deploy
   🙌 Function image built: image-registry.openshift-image-registry.svc:5000/demo/test-function:latest
   ✅ Function updated in namespace "demo" and exposed at URL:
🕘 https://test-function-demo.apps.zroubali.serverless.devcluster.openshift.com
```

The `deploy` command finished. There is a clock (🕘) icon in the final message, which is confusing. It should be removed or replaced by another icon marking success.

**Comment by ShlokMohanty** [comment]
@zroubalik is this issue completed if yes then we could close this issue right?

**Comment by zroubalik** [comment]
@ShlokMohanty this issue hasn't been yet fixed.

**Comment by Rohith-Raju** [comment]
@zroubalik I would like to work on this issue

**Comment by zroubalik** [comment]
@Rohith-Raju awesome!

**Comment by Rohith-Raju** [comment]
Hey, @zroubalik I tried recreating this issue by deploying the function to the docker hub. Even though my credentials are proper it throws an error saying `Incorrect credentials, please try again`. Could you please confirm

**Comment by Rohith-Raju** [comment]
Should we remove the clock icon? or replace it with another icon like this ➡️?

**Comment by lkingland** [comment]
We're likely going to be replacing the spinner/progress system entirely in favor of a new shared library in development that includes a logger and a progress reporter

cc @gauron99

**Comment by lkingland** [comment]
@Rohith-Raju I am going to switch assignees on this issue, since we're removing the spinner entirely, and this issue will therefore not be pertinent.

There's [a growing list of "good first issues" ](https://github.com/knative/func/issues?q=is%3Aissue+is%3Aopen+label%3Akind%2Fgood-first-issue)if you still have time to help out
