### ISSUE TITLE
Making network `host` not the default option for linux

### ISSUE THREAD

**Issue by salaboy** [knative/func#1525]
Is there any reason why `host` is the default option for linux? 

https://github.com/knative/func/blob/main/buildpacks/builder.go#L124-L126

Based on the docs (https://docs.docker.com/network/host/ ), this option is good for performance when the container is going to handle a large number of ports, but I don't think we have that scenario here. 

By commenting out this check I managed to get `func` build containers on GitPod and avoid this issue: 
https://github.com/gitpod-io/gitpod/issues/16022

**Comment by salaboy** [comment]
@matejvasek thanks a lot for helping me to troubleshoot this, I wonder if you know who might know why we added that check in the first place.

**Comment by matejvasek** [comment]
@salaboy it is used so docker connection tcp socket on 127.0.0.1 works.
Most people use unix socket/winpipe still it is nice to make also tcp work by default.
AFAIK problem is user-namespace-enable + host-network, could you add check for user namespaces?

**Comment by matejvasek** [comment]
@salaboy could you modify condition so network=host is used only if user ns are not enabled?

**Comment by salaboy** [comment]
@matejvasek is there any way to check for that?

**Comment by matejvasek** [comment]
I don't know.

**Comment by salaboy** [comment]
Ok.. I am sure the answer is here.. so I will do my research: https://docs.docker.com/engine/security/userns-remap/#disable-namespace-remapping-for-a-container

**Comment by lance** [comment]
@salaboy any chance to look into this?
