### ISSUE TITLE
On Cluster build failing on deploy task with `Error: not built`

### ISSUE THREAD

**Issue by jrangelramos** [knative/func#1535]
On Cluster builds are failing on deploy task with message `Error: not built`.
On the `Deploy` implementation,`func` client now ensures the function is built and source files are not modified (since last built) by comparing a generated hash based on source file modified timestamps (stored on `.func/built` after build).

For on-cluster builds, the build task (buildpack and s2i) does not generate and save the hash on `.func/built` thus causing the following  task "deploy" to fail.

**Comment by jrangelramos** [comment]
The tekton task build does not produce a `.func/built` file with build stamp just as func local build.. thus the on cluster deploy task is falling on the condition below
https://github.com/knative/func/commit/958429c2#diff-4b667feae66c9d46b21b9ecc19e8958cf4472d162ce0a47ac3e8386af8bbd8cfR1002-R1005

Here some possible approaches to fix it:
* Add a flag on deploy, for example `--force` or `--bypass-build-check` (to bypass that check) and update tekton deploy task to use it
* Add some flag or command on func build to bypass build and just calculate the built hash and create `.func/built` so that it could be used on the build tekton task

**Comment by lkingland** [comment]
My guess here is that this is a case that needs to be implemented for the `--build=false` case, not a new flag needed.

In particular, this looks correct to me: https://github.com/knative/func/blob/main/pipelines/resources/tekton/task/func-deploy/0.1/func-deploy.yaml#L30

I will look into it further, but the `--build=false` directive should probably also include the case in which a deploy is requested even though the function has not been locally built (but of course the image would be available)
