### ISSUE TITLE
Using the "func run" CLI command to locally run a Knative function which uses a configmap to set environment variables results in required environment variables not being mounted correctly

### ISSUE THREAD

**Issue by Paul1334** [knative/func#1536]
Context
---
I have a Knative function which mounts the values of a configmap as environment variables within the underlying container.
When deploying the Knative function as a Knative service within a cluster, which already contains the configmap in question, the environment variables are pulled and mounted successfully from the configmap into the container.

When running a Knative function locally to test the function with a "func run", there is no ConfigMap available as the function is simply running in the OCI container locally with no access to a ConfigMap. 

This means that the locally running container does not have the required environment variables mapped, which results in the application failing.

Example
---
In this example the ConfigMap is named "environment-info" and this configmap contains the following in its data field:
```
StorageBucketName:
----
test-storage-bucket
```
I have pulled down the environment variables set on the locally running function container. The value of the environment variable is set to the following:

Input
`docker exec 0db7989ec1bd /usr/bin/env
`
Output
`StorageBucketName={{ configMap:environment-info:StorageBucketName}}`

When running the Knative function as a Knative service within a cluster which already contains the configmap, the same environment variable is set correctly

Output
`StorageBucketName=test-storage-bucket
`

Is there a recommended solution for this issue? It looks like there's some templating resolution somewhere as part of the func deploy process?

**Comment by zroubalik** [comment]
@Paul1334 I am not sure I fully understand what do you actually propose. What should be the ENV value when running the function locally?

**Comment by Paul1334** [comment]
It could be that there is a flag on the func run command for choosing a config file "func.yaml". So you could have a config for local deployment and one for remote and have the option to choose which one is required.

Or attempt to resolve the value from the remote cluster and if it can't it fails to run. That way it fails fast rather than supplying a templated string e.g StorageBucketName={{ configMap:environment-info:StorageBucketName}} to the container, which then means the image is built, the container starts up and only then the underlying application falls over due to the environment variable being incorrect.

**Comment by Paul1334** [comment]
@zroubalik unfortunately I'm unable to contribute at this time with the required code changes, but happy to help steer the ship in terms of requirements.

I think the attempt to resolve the value from the remote cluster before building the image first is a good step. Then if it can't connect to the cluster or it fails to find the ConfigMap/required values from the ConfigMap, it fails before attempting the build and informs the caller the reason behind the failure with a clear error message.
