### ISSUE TITLE
On Cluster builds (from Git) fails with "different registry than the current configured"

### ISSUE THREAD

**Issue by jrangelramos** [knative/func#1541]
It seems there is a mismatch on the logic behind build process On Cluster and local.
On local build, let's say using the below steps, `func.yaml` get updated with the built image and the registry ...
```
$ func create -l node /tmp/samplefunc
Created node function in /tmp/samplefunc
$ func build -p /tmp/samplefunc -r ttl.sh/jrangelramos-sample
   🙌 Function image built: ttl.sh/jrangelramos-sample/samplefunc:latest
$ awk '/^image:|^registry:/' /tmp/samplefunc/func.yaml 
registry: ttl.sh/jrangelramos-sample
image: ttl.sh/jrangelramos-sample/samplefunc:latest
$ func deploy -p /tmp/samplefunc --build=false
   ✅ Function created in namespace "sample-test" and exposed at URL: 
   https://samplefunc-sample-test.apps.mycluster.net
```

A build on cluster (from git) does not follow the same pattern. Build tasks just update the  `image` field on `func.yaml` and leave the `registry` untouched. This is causing deploy process to fails by stating the registry is different than the current configured.

```
$ func deploy -p /tmp/TestBasicGit521085418/001/test-func-basic-gittj42g -r ttl.sh/knfunccejia9x1 --remote --verbose --git-url http://func-git.build-test.svc.cluster.local/test-func-basic-gittj42g.git
Creating Pipeline resources
Running Pipeline Task: Fetching git repository with the function source code
Running Pipeline Task: Building function image on the cluster
Running Pipeline Task: Deploying function to the cluster
Error: failed to run pipeline: function pipeline run has failed with message: 

Warning: function has current image 'ttl.sh/knfunccejia9x1/test-func-basic-gittj42g:latest' which has a different registry than the currently configured registry 'image-registry.openshift-image-registry.svc:5000/build-test'. The new image tag will be 'image-registry.openshift-image-registry.svc:5000/build-test/test-func-basic-gittj42g:latest'.  To use an explicit image, use --image.
⬆️  Deploying function to the cluster
Waiting for Knative Service to become ready
deploy error: knative deployer failed to wait for the Knative Service to become ready: RevisionFailed: Revision "test-func-basic-gittj42g-00001" failed with message: Unable to fetch image "image-registry.openshift-image-registry.svc:5000/build-test/test-func-basic-gittj42g:latest": failed to resolve image to digest: HEAD https://image-registry.openshift-image-registry.svc:5000/v2/build-test/test-func-basic-gittj42g/manifests/latest: unexpected status code 404 Not Found (HEAD responses have no body, use GET for details).
```

**Comment by lkingland** [comment]
That message is a warning:
```
Warning: ...  the new image tag will be 'image-registry.openshift-image-registry.svc:5000/build-test/test-func-basic-gittj42g:latest'.  To use an explicit image, use --image.
```
I am not saying they are not related; perhaps it is indeed a logic mismatch as you say.  I just wanted to point out that that message is a warning; not the _direct_ reason this is failing.

My guess is that there is a logic error somewhere in how the image is being handled (this is a topic of our call tomorrow).   Just note that those messages are intended to warn the user when they are doing something that may cause them confusion, but is nonfatal

**Comment by lance** [comment]
> Just note that those messages are intended to warn the user when they are doing something that may cause them confusion, but is nonfatal

Yes - in this case, the on-cluster build appears to be defaulting to the OpenShift internal registry (presumably this only happens on the OpenShift version of the build), when `registry` is unset. 

```
Unable to fetch image "image-registry.openshift-image-registry.svc:5000/build-test/test-func-basic-gittj42g:latest": failed to resolve image to digest: HEAD https://image-registry.openshift-image-registry.svc:5000/v2/build-test/test-func-basic-gittj42g/manifests/latest: unexpected status code 404 Not Found (HEAD responses have no body, use GET for details).
```

@jrangelramos can you get any more information from the pipeline logs? It seems that, if the image is built and pushed to the internal registry it still should be discoverable by the `Service`. I also wonder if this issue is specific to the OpenShift distribution. Have you tried with vanilla `func`?

**Comment by jrangelramos** [comment]
Hey @lance, it happens with vanila `func`, actually is happening on CI currently, on **KinD** (see https://github.com/knative/func/actions/runs/4126201486/jobs/7171819367) . It occurs on `deploy` phase (which uses `func` image from ghcr.io) . 

Actually, this can be reproduced on local builds as well. We just need to reproduce the oncluster build behavior, by doing a `func build` and then a `func deploy`, but leaving the `registry` field empty on `func.yaml` with the following steps:
```
func create -l node /tmp/testfunc
func build -r ttl.sh/jrangelramos -p /tmp/testfunc
grep -v ^registry: /tmp/testfunc/func.yaml > /tmp/f.tmp && cp /tmp/f.tmp /tmp/testfunc/func.yaml 
func deploy --build=false -p /tmp/testfunc
```

**Comment by jrangelramos** [comment]
The image is built and pushed to the registry user has chosen on `func build -r myregistry.io/myuser` but since it does not recovery the registry from `func.yaml` it defaults to openshift internal and fails to deploy, once there is no function pushed on ocp internal repo.
