### ISSUE TITLE
Refactor repository layout - make it more hierarchical

### ISSUE THREAD

**Issue by zroubalik** [knative/func#1547]
The current repository layout is quite flat and sometimes it might be very confusing to find the correct code block. In the root of the https://github.com/knative/func directory there are packages related to `func` functionality, `.dotted` directories, vendor/thirdparty directories, metadata files test packages, generators and also `func` related files put directly in the root etc. Everything.

**Current state:**
```
.chglog
.codecov.yaml
.git
.gitattributes
.github
.gitignore
.golangci.yaml
.ko.yaml
.unicode-control-characters.config.py
.versionrc
.vscode
AUTHORS
CHANGELOG.md
CODE-OF-CONDUCT.md
LICENSE
Makefile
OWNERS
OWNERS_ALIASES
README.md
builders
buildpacks
client.go
client_int_test.go
client_test.go
cmd
config
config_test.go
docker
docs
filesystem.go
filesystem_test.go
function.go
function_envs.go
function_envs_unit_test.go
function_git.go
function_git_unit_test.go
function_labels.go
function_labels_unit_test.go
function_migrations.go
function_migrations_unit_test.go
function_options.go
function_options_unit_test.go
function_test.go
function_unit_test.go
function_volumes.go
function_volumes_unit_test.go
generate
go.mod
go.sum
hack
http
instances.go
instances_test.go
invoke.go
job.go
k8s
knative
mock
openshift
pipelines
plugin
progress
repositories.go
repositories_test.go
repository.go
repository_test.go
s2i
schema
sortedset.go
ssh
template.go
templates
templates.go
templates_test.go
test
testdata
testing
third_party
utils
vendor
zz_filesystem_generated.go
```

I'd like to refactor the repository and bring more hierarchy into it, I'd put source code related to `func` functionality into `pkg/...` as it is common with other Go based projects, making the root more simple and clear. Inside `pkg` directory I'd also create a new package for `client*.go`, `function*.go`, `repositor*.go` and `template*.go` etc.

**Desired state:**
```
.chglog
.codecov.yaml
.git
.gitattributes
.github
.gitignore
.golangci.yaml
.ko.yaml
.unicode-control-characters.config.py
.versionrc
.vscode
AUTHORS
CHANGELOG.md
CODE-OF-CONDUCT.md
LICENSE
Makefile
OWNERS
OWNERS_ALIASES
README.md
cmd
docs
generate
go.mod
go.sum
hack
pkg
plugin
schema
test
testdata
testing
third_party
vendor
zz_filesystem_generated.go
```

As a follow up item, I'd like to unify all `test*` stuff under one directory.

**Comment by drriguz** [comment]
Yes, it's better to keep the hierarchy consistent with other Knative projects like [Eventing](https://github.com/knative/eventing) and [Serving](https://github.com/knative/serving).

**Comment by lkingland** [comment]
As for the `test*` stuff, I would put `testing` and `testdata` into `pkg` because the former is a package specifically imported into tests with helper functions, and `testdata` needs to remain named as such because it is a go idiom for where data is kept for tests.  The `test` directory which would then remain at the root contains @jrangelramos ' E2E tests, so that might be a good place to leave that one.
