### ISSUE TITLE
Deploy functions to a dedicated namespace

### ISSUE THREAD

**Issue by vvavepacket** [knative/func#1567]
I noticed all functions get deployed to `default` namespace. How can we configure the installation or yamls such that any serving resources or new functions get deployed to say to a `my-knative` namespace?

**Comment by lkingland** [comment]
```
func deploy --namespace my-knative
```

You should be able to specify the target namespace using the flag `--namespace` on the deploy command.
The default namespace should be pulled from your current kubernetes context `kubectl config current-context`
Re-deploying a function will re-deploy to the same namespace to which it was originally deployed.
Please open an issue if you notice any bugs 👍🏻
