### ISSUE TITLE
Ensure CloudEvent metadata is valid, not just the payload / data structure

### ISSUE THREAD

**Issue by matzew** [knative/func#1628]
Let's assume we have a service like the [canonical demo](https://github.com/knative/func/blob/main/templates/quarkus/cloudevents/src/main/java/functions/Function.java#L19), with the following signature:

```java
    public CloudEvent<Output> function(CloudEvent<Input> input)
```

We can pass in a binary CE like:

```
curl "http://localhost:8080/" -X POST \
  -H "Content-Type: application/json" \
  -H "Ce-SpecVersion: 1.0" \
  -H "Ce-Type: my-type" \
  -H "Ce-Source: cURL" \
  -H "Ce-Id: 42" \
  -d '{"message": "Hello there."}'
```

The only validation we really have is that the "strucutre" matches, the structure of the `Input` (meaning a `message` property as part of the JSON payload).

It would be good if we can also restricut the input on certain values, based on CloudEvent metadata, such as `type`, `source`, or even `specversion`.

**Comment by matejvasek** [comment]
@matzew I not sure what you mean but you can already do dispatch on `ce-type`:
```java
@Funq
@CloudEventMapping(trigger = "desired-ce-type")
CloudEvent<Out> foo(CloudEvent<In> in );

@Funq
@CloudEventMapping(trigger = "some-other-ce-type")
CloudEvent<Out2> bar(CloudEvent<In2> in );
```
