### ISSUE TITLE
Unable to run or deploy python function using s2i builder on Windows Platform

### ISSUE THREAD

**Issue by jrangelramos** [knative/func#1639]
On Windows platform a python function, built with s2i, does not deploy neither run locally, due app.sh file permission

```
PS C:\Users\jeramos\python-func> func deploy --builder=s2i
        Service output:
        ---> Running application from script (app.sh) ...
        /usr/libexec/s2i/run: line 40: /opt/app-root/src/app.sh: Permission denied
        ---> Running application from script (app.sh) ...
        /usr/libexec/s2i/run: line 40: /opt/app-root/src/app.sh: Permission denied
        ---> Running application from script (app.sh) ...
        /usr/libexec/s2i/run: line 40: /opt/app-root/src/app.sh: Permission denied
        ---> Running application from script (app.sh) ...
        /usr/libexec/s2i/run: line 40: /opt/app-root/src/app.sh: Permission denied
        ---> Running application from script (app.sh) ...
        /usr/libexec/s2i/run: line 40: /opt/app-root/src/app.sh: Permission denied
```

**Comment by matejvasek** [comment]
Will look into it.

**Comment by jrangelramos** [comment]
@matejvasek I just retried and I got
```
        Service output:
        ---> Running application from script (app.sh) ...
        /usr/libexec/s2i/run: /opt/app-root/src/app.sh: /bin/sh^M: bad interpreter: No such file or directory
        /usr/libexec/s2i/run: line 40: /opt/app-root/src/app.sh: Success
```

**Comment by matejvasek** [comment]
@jrangelramos have you used proper `func` build with templates zip file generated on Linux?

**Comment by matejvasek** [comment]
> @jrangelramos have you used proper `func` build with templates zip file generated on Linux?

And if for some reason you have to regenerate template zip file on Windows you should set up `LF` as `EOL` for `git.

**Comment by jrangelramos** [comment]
I just cloned main and ran a `make build` on Windows powershell..

**Comment by matejvasek** [comment]
@jrangelramos  Try `git config --global core.eol lf` and clone and build.

**Comment by matejvasek** [comment]
But it's weird I don't think that `make build` should regenerate templates zip array.

**Comment by matejvasek** [comment]
Ok for some reason `make build` also regenerates the zz file.

**Comment by jrangelramos** [comment]
that's correct Matej.. it worked fine after setting git defaults on win. thanks
