### ISSUE TITLE
Where to test func templates on top of S2I images

### ISSUE THREAD

**Issue by frenzymadness** [knative/func#1675]
Since func provides templates for language stacks supported by S2I and it's possible to use S2I container images as builders, it makes sense to me to test that func, templates, and container images work together. I see two possibilities but each has some disadvantages.

## Test it here

* :heavy_plus_sign: Changes in templates are immediately tested with all (supported) S2I builders.
* :heavy_plus_sign: You know the func software much better. You can test multiple ways of installation.
* :heavy_plus_sign: There is no need to set up anything special for S2I - you'll be testing the process from customer point of view.
* :heavy_minus_sign: Maintenance of a list of supported S2I images (combinations of language versions and supported platforms). But because I'm sure we won't support all of them, the same applies also to the second option.

## Test it in S2I CI

* :heavy_plus_sign: Templates are tested with new container images before the images are published.
* :heavy_minus_sign: func depends on Docker and I'm not sure how easy would be to use it in our CI.
* :heavy_minus_sign: func is not packaged as RPM and might not be easy to build from source in our CI. Downloading executable binary might (not) be an option for us.

I think that better would be to test this here in the CI and I'm willing to help with that and with the maintenance of supported S2I images (depends on what your plan is).

What do you think about it?

**Comment by frenzymadness** [comment]
This might be interesting for @zmiklank @phracek @pkubatrh and @hhorak

**Comment by lance** [comment]
@frenzymadness please take a look at https://github.com/knative/func/blob/main/test/e2e/scenario_runtime-http_test.go. I believe this is doing what you are looking for. It does an end to end test for all runtimes and all builders.

**Comment by frenzymadness** [comment]
Thanks for the response. I've found one link to Python container image here: https://github.com/knative/func/blob/a72431bd6508e14cdee2205c033b3f9e0bef0926/pkg/builders/s2i/builder.go#L45

Would it make sense to update tests in a way that they would run with more than one Python / RHEL combination?

**Comment by lance** [comment]
> Would it make sense to update tests in a way that they would run with more than one Python / RHEL combination?

Perhaps, although that might be better in [openshift-knative/kn-plugin-func](https://github.com/openshift-knative/kn-plugin-func) - the midstream repo for OpenShift Serverless. What additional builder images are there for Python? Note, we are also only using a single Node.js builder image as well.

**Comment by frenzymadness** [comment]
> What additional builder images are there for Python?

We provide images for all available Pythons in RHEL:
* Python 2.7, 3.6 and 3.8 on RHEL 8
* Python 3.9 and 3.11 on RHEL 8 and 9.
* Python 3.11 also on Fedora.

**Comment by frenzymadness** [comment]
The idea here is to improve the testing by extending the matrix of tested combinations of Python and the platforms they are provided for. Feel free to close the issue if you are not interested in that.
