### ISSUE TITLE
Add shorthand for 'func deploy --remote' to allow 'func deploy -R' according to the Synopsis 

### ISSUE THREAD

**Issue by grafvonb** [knative/func#1719]
According to the Synopsis of `func deploy`:
```
SYNOPSIS
	{{rootCmdUse}} deploy [-R|--remote] [-r|--registry] [-i|--image] [-n|--namespace]
	             [-e|--env] [-g|--git-url] [-t|--git-branch] [-d|--git-dir]
	             [-b|--build] [--builder] [--builder-image] [-p|--push]
	             [--platform] [-c|--confirm] [-v|--verbose] [--build-timestamp]
```
`func deploy --remote` should have a shorthand `func deploy -R` which is not implemented currently.

**Comment by grafvonb** [comment]
@lance Actually it is a mini-bug. How do we handle this?

**Comment by lance** [comment]
/kind bug
@grafvonb I don't think it's bad enough to need a backport. I think it should just be a simple fix.

**Comment by grafvonb** [comment]
@lance maybe a good 'first-first-issue' for a new commiter?
