### ISSUE TITLE
Is it possible to configure GPU resources? Or at least run on specific machine type?

### ISSUE THREAD

**Issue by WaterKnight1998** [knative/func#1726]
This would enable Serverless GPU Inference. We could share GPU nodes for different requests. 

Maybe some projects doesn't make use of GPU the full day

**Comment by lance** [comment]
GPU utilization should be configured at a lower level than function deployment, but yes, it can be done. I have not personally tested this, but here is an example of how this might work.

* Use something like NVIDA's gpu feature discovery on your cluster: https://github.com/NVIDIA/gpu-feature-discovery/blob/main/README.md
* If I understand correctly, this will allow you to add labels to your deployments to utilize gpu
* Use `func config labels add` to add these labels to your function
* Deploy the function, and the labels should be correctly set on the running Knative `Service`

**Comment by lance** [comment]
Closing this issue as it's not relevant to the `func` backlog.
