### ISSUE TITLE
Function starting aborted after about 30 seconds.

### ISSUE THREAD

**Issue by rabejens** [knative/func#1760]
I have a function template which takes longer than 30 seconds to become ready. Is it possible to increase the timeout in `func.yaml` to mitigate this?

Followup 1:

I configured my `knative-serving` to set the `scale-to-zero-grace-period` to 600s (10 minutes) but this did not change anything. It is still scaling to zero after 30 seconds.

Followup 2:

Even disabling scale-to-zero completely has it killed after about 30 seconds.

Followup 3:

As a workaround, I currently made liveness and readiness instantly return 200 OK even though the function is still initializing. While this works for the time being, this is not optimal.

**Comment by lance** [comment]
I have tried to replicate this using a simple function. I was not able to replicate it with a 60 second delay, but a 2 minute delay resulted in the failure message, "Initial scale was never achieved". Is this what you are seeing too?

<details><summary>Node.js function with liveness and readiness probes with 2 minute delay</summary>

```js

const handle = async (context, body) => {
  return { "message": "Hello world!" };
}

// Wait until the delay completes before returning 200 OK
const readiness = (request, reply) => {
  if (ready) {
    reply.statusCode = 200;
    return 'Yeah boyeee';
  } else {
    reply.statusCode = 503;
    return 'Not ready';
  }
}

const liveness = readiness;

// Utility function to simulate a delay
const sleep = async (ms) => {
  return new Promise(resolve => setTimeout(resolve, ms));
}

let ready = false;
// 120 second delay to simulate a long startup time
sleep(120000).then( _ => { ready = true; }).catch( e => { console.error(e); })

// Export the function
module.exports = { handle, readiness, liveness };
```
</details>

Running this function yields

```console
kn service list
NAME   URL                                     LATEST      AGE   CONDITIONS   READY   REASON
foo    http://foo.default.127.0.0.1.sslip.io   foo-00005   43h   1 OK / 3     False   RevisionFailed : Revision "foo-00006" failed with message: Initial scale was never achieved.
```
