### ISSUE TITLE
Dapr installation times out in CI

### ISSUE THREAD

**Issue by lkingland** [knative/func#1806]
The installation of the Dapr runtime is failing in GitHub actions, just after "pulling images from docker hub" is printed.

**Comment by matejvasek** [comment]
@lkingland is this because registry outage or some IP throttling?

**Comment by matejvasek** [comment]
I guess this is know issue when GH Action cannot pull from `docker.io` because too many pulls.

**Comment by matejvasek** [comment]
I don't know why but it seems dapr installation just started working on its own.

**Comment by lkingland** [comment]
> I don't know why but it seems dapr installation just started working on its own.

That's good.  I figured it was a transient failure, probably throttling as you guessed as well.

We have some tech debt here:  we're dependent on both docker.io and ttl.sh for our CI.
