### ISSUE TITLE
Better handling for Multiple Functions in a Single Repository

### ISSUE THREAD

**Issue by darthkali** [knative/func#1813]
**Goal:**
I'm working on supporting multiple functions, primarily Spring Boot applications, in a single repository. This includes being able to share common code like domain classes and defining dependencies only once. Ultimately, these functions should be able to be deployed as individual functions into the Kubernetes cluster.

**Current Approach:**
Currently, I'm splitting the functions into separate modules, with a main `pom.xml` and each module having its own module pom.xml. By specifying `BP_MAVEN_BUILT_MODULE` in the `func.yaml`, I can indicate the module to be built and it is correctly deployed.

```
├── module-core
│   ├── src
│   │   ├── ...
│   ├── pom.xml
├── module-func-1
│   ├── src
│   │   ├── ...
│   │   |   ├── Application.java
│   ├── pom.xml
├── module-func-1
│   ├── src
│   │   ├── ...
│   │   |   ├── Application.java
│   ├── pom.xml
├── pom.xml
├── func.yaml
```

**Problem:**
The main problem is that I have to adjust the `func.yaml` each time, as it has to be located next to the main `pom.xml`. However, I need a separate `func.yaml` for each function.

**Possible Solution Approach:**
One possible solution could be to use the path option provided by [pack](https://buildpacks.io/docs/tools/pack/cli/pack_build/#options). With this, one can refer to a main folder from a subfolder. Another possibility could be to allow multiple functions in the func.yaml, similar to how the [Serverless Framework](https://www.serverless.com/framework/docs/providers/aws/guide/functions) allows for AWS Lambda.

I look forward to feedback and potential solutions to this problem. Thanks

**Comment by lkingland** [comment]
Hello @darthkali,

This seems like it could perhaps be something that needs to change in the way Spring Boot functions are built and deployed.
There is a 1:1 correlation between a Function and its `func.yaml`.  The yaml is the metadata for a single Function.
However, there should be no need for this to reside at the repository root.  Functions can be defined to reside within a subdirectory of a repository.

This may be anathema to the way you are trying to set up your project, but note that a Funciton is conceptually a completely separate, independent service.  As such it should not share any build-time dependencies with other Functions unless those are structured as independent projects importing each-other as dependencies.  So this might be a situation that doesn't quite fit your desired setup.
