### ISSUE TITLE
On cluster build: Don't reference tasks from knative/func git repo

### ISSUE THREAD

**Issue by zroubalik** [knative/func#1858]
Pipelines used by the on cluster build implemented by Standard Tekton approach reference func related tasks hosted on this repo. The only approach that we can use with the Standard Tekton is [the Git resolver](https://tekton.dev/docs/pipelines/resolution-getting-started/) - it fetches the whole repo and then use tasks in this repo:
https://github.com/knative/func/blob/79c36eefdc50d4fdea140a2a9c0449a18bfb9511/pkg/pipelines/tekton/templates.go#L37-L69

On the other hand, Pipelines as Code apporach that we use for a part of on cluster build also supports [URL resolver](https://pipelinesascode.com/docs/guide/resolver/#remote-http-url) - then we can just reference a single file hosted in some repo and the whole resolving is much faster:
https://github.com/knative/func/blob/79c36eefdc50d4fdea140a2a9c0449a18bfb9511/pkg/pipelines/tekton/templates.go#L29-L31

Using Git resolver might be problematic when the referenced task is hosted in a large git repo - it takes some time to fetch the whole repo. I opened issue on Tekton to add URL resolver - https://github.com/tektoncd/pipeline/issues/6920

We should mitigate the problem with the lengthy resolver, there are a couple of solutions:
- wait until URL resolver is added to Tekton (this might take some time)
- move tasks to another Git repo that will only host these tasks (suboptimal solution)
- add Func tasks to Tekton Hub and then just use Hub Resolver which already exists (I think this is the cleaniest solution from Tekton POV)

Affected tasks:
- func-buildpacks
- func-s2i
- func-deploy

**Comment by matejvasek** [comment]
@phutaneVinayak This is odd, what version of func do you use?

**Comment by matejvasek** [comment]
What command did you invoke?

**Comment by phutaneVinayak** [comment]
Hi @matejvasek ,
I am using kn-func version v1.10.0.

I try below command 
`kn-func deploy --remote `

Which help to deploy function from current folder to cluster. I am trying to on cluster build.

Can you give me bit more perfect way to do it. It would be much helpful.

**Comment by matejvasek** [comment]
You need update.

**Comment by matejvasek** [comment]
On v1.10.0 you need to install the tasks manually using `kubectl apply`.

**Comment by matejvasek** [comment]
They are under https://github.com/knative/func/tree/main/pkg/pipelines/resources/tekton/task .
But v1.11.0 should resolve it.

**Comment by phutaneVinayak** [comment]
Hi @matejvasek ,

Really really thank you :) . I try both way.

**Comment by phutaneVinayak** [comment]
Hi @matejvasek ,

I updated kn-func to 1.11.0 It worked 👍 

thanks a lot.
