### ISSUE TITLE
Proposal: A custom writer to print output from `func` instead of `fmt.Printf`

### ISSUE THREAD

**Issue by zroubalik** [knative/func#1865]
Use a custom writer to print output from `func` instead of `fmt.Print`, this common writer would be used for all messages written by the tool. This would allow to set unified look an feel, verbosity from a single place.

For example see Tekton `tkn` CLI which uses this technique.

**Comment by cardil** [comment]
See the [Knative CLI Developer Experience](https://docs.google.com/document/d/15ZY2djwpALUXb-sRag3OksN42NR8zYTSPOggdGawzPY) proposal, which covers this topic.
