### ISSUE TITLE
Proposal: Implement Knative (Functions) GitHub Action

### ISSUE THREAD

**Issue by zroubalik** [knative/func#1866]

**Comment by nitishchauhan0022** [comment]
Would like to know more about this, what can be added, any proposal or desired outcome?

**Comment by lkingland** [comment]
Hello @nitishchauhan0022,

This is referring to creating a reusable GitHub Action which installs the latest `func` binary and runs `func deploy` or `func build`.  Presuming this is triggered when a PR is merged, it would complete a GitHub-based CI/CD pipeline.

This is a feature which we are eager to create, but do not currently have the bandwidth to begin.

**Comment by nitishchauhan0022** [comment]
Great, I will give it a try.
