### ISSUE TITLE
Node Function Build with local dependencies

### ISSUE THREAD

**Issue by jonirap** [knative/func#1880]
When building node functions, allow for installing of local packages located outside the context of the function.
Paketo buildpacks context needs to be changed

**Comment by matejvasek** [comment]
@jonirap is this possible as of now just with paketo buildpacks and `pack` CLI?

**Comment by jonirap** [comment]
It is possible, but not with the `func build` command

**Comment by matejvasek** [comment]
What is the command? `pack ...`?

**Comment by jonirap** [comment]
I'm using the `func` CLI and the `build` command to create the function images. Behind the scenes this uses `pack` but I don't use it directly.
Do you suggest using it directly instead of using the `func` CLI?
This also means that each time I deploy I can't count on the CLI automatically building the image for me

**Comment by matejvasek** [comment]
@jonirap I mean: if I know exact `pack` flags I could more easily port it to `func`.

**Comment by matejvasek** [comment]
Also could you please provide sample project that does not run now but that should work.

**Comment by matejvasek** [comment]
@jonirap could you please provide some sample project that is not compiling but it should be?

**Comment by jonirap** [comment]
Yes, It'll take me some time, the project I have is not open source
