### ISSUE TITLE
Too strict or incorrect JSON schema definition of func.yaml

### ISSUE THREAD

**Issue by fc7** [knative/func#1887]
When editing func.yaml in VS Code and the Knative extension, many error messages are displayed about supposedly missing mandatory properties or even properties that are not allowed. 

It uses [this schema](https://raw.githubusercontent.com/knative/func/latest-release/schema/func_yaml-schema.json).

Either the auto-generated func.yaml is invalid or the schema is too strict (or partly inaccurate). As far as I can see, the latter is the case.

Here are some examples of the messages I get:

<img width="709" alt="Screenshot 2023-07-25 at 18 38 30" src="https://github.com/knative/func/assets/85877/8fe05081-4dee-42f6-8637-1ac2b3829779">

---

<img width="666" alt="Screenshot 2023-07-25 at 18 38 42" src="https://github.com/knative/func/assets/85877/569fc8ff-7f04-4bac-923f-3cc1cc1bfcc1">

---

<img width="645" alt="Screenshot 2023-07-25 at 18 38 54" src="https://github.com/knative/func/assets/85877/30c67320-e8b0-432f-9b56-ddf005179198">

---

<img width="674" alt="Screenshot 2023-07-25 at 18 39 02" src="https://github.com/knative/func/assets/85877/59b67ee3-fb5f-4c36-b11a-00232b083334">

**Comment by lkingland** [comment]
Thanks for reporting the issue.  We do need to revisit the schema generation and ensure it's working as intended

**Comment by matejvasek** [comment]
@fc7 has been this fixed?

**Comment by matejvasek** [comment]
@fc7 I believe this should be fixed now.

**Comment by fc7** [comment]
@matejvasek  It looks much better now. I am opening various `func.yaml` that were generated in older experiments and I only see a few minor schema-compliance issues.

In one case I had:
```yaml
invocation:
  format: http
```
--> Property invocation is not allowed.

I guess the above should now be replaced by `invoke: http`.

The next minor thing I found was:
```yaml
build:
  buildpacks:
  - docker.io/paketocommunity/rust
  builder: ""
  buildEnvs: []
```
--> Value [of "builder"] is not accepted. Valid values: "pack", "s2i".

I guess the current version of `func` would no longer generate any of the above. If it is also backwards-compatible with older projects (or at least outputs decent warnings), then all is fine.

**Comment by lkingland** [comment]
Thanks @fc7 for checking.  We intend each version of func.yaml to have an auto-migration, so this should have migrated automatically based on the value of `specVersion`.   It is also on the list of things we need to improve, however, as it is a fairly naive implementation at present.  Thanks again
