### ISSUE TITLE
Deploying Container runAsNonRoot Error

### ISSUE THREAD

**Issue by lkingland** [knative/func#1913]
When deploying a new Function to a k3s cluster using the host builder, the container is unable to start due to a permissions error as follows:

```Error: container has runAsNonRoot and image will run as root```

we are now[ deliberately using a more secure configuration](#1886) than the default.  This is causing some errors because our containers expect to be able to run as root.   We can hopefully maintain this higher security standard since we are building the containers, and can configure them at build-time to a non-root user

**Comment by lkingland** [comment]
This is also apparently also affecting python functions built on-cluster

**Comment by lkingland** [comment]
This issue is now fixed for the `host` builder in #1921, but we should check if the Pack and S2I builders are affected before closing the issue

**Comment by gauron99** [comment]
id like to work on this
/assign

**Comment by gauron99** [comment]
I tested create-build-deploy with the following:
```
-- KIND
❯ k version --short
Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.27.1
with upstream func Aug 25 at 1000 GMT+2

- Tested locally (without --remote) with pack -- OK
- Tested locally with s2i -- OK
- Tested remotely (w/ --remote) with s2i -- OK
- Tested remotely with pack -- OK
```

```
-- OCP aws cluster
❯ oc version
Client Version: 4.13.9
Kustomize Version: v4.5.7
Server Version: 4.13.5
Kubernetes Version: v1.26.6+f245ced
with upstream func Aug 25 at 1000 GMT+2

- Tested locally (without --remote) with pack -- OK
- Tested locally with s2i -- OK
- Tested remotely (w/ --remote) with s2i -- OK
- Tested remotely with pack -- OK
```

I didn't encounter an error once related to a sudo permission issue

**Comment by lkingland** [comment]
That's great news; thanks for checking @gauron99 that we can keep the tighter security
