### ISSUE TITLE
Request for tolerations, nodeSelector and affinity to be allowed to configure in func.yaml

### ISSUE THREAD

**Issue by Jaryllan** [knative/func#1943]
Based on the document of func.yaml in https://github.com/knative/func/blob/main/docs/reference/func_yaml.md. It does not specify or show ways to configure the tolerations, nodeSelector and affinity. Due to this the app have to be manually patch after the deployment with func cli.

So, I would like to request this 3 "tolerations, nodeSelector and affinity" to be allowed to configure in func.yaml.

**Comment by lkingland** [comment]
Hello @Jaryllan thank you for your post.

Yes I believe this, as well as a few other configuration options, are expected to be exposed through the Functions abstraction.

Until we have these settings exposed, patching the service after a deploy is probably the best option.

**Comment by gabbler97** [comment]
Dear @lkingland,
Thank you for your answer!
