### ISSUE TITLE
Error: "" is not a known builder. Available builders are "pack" and "s2i"

### ISSUE THREAD

**Issue by matzew** [knative/func#1970]
```
func version  
v0.38.0-12-g0d6e2106
```

Doing `func config`, I am getting **Error: "" is not a known builder. Available builders are "pack" and "s2i"**

```
func config
? What do you want to configure? Git
? What operation do you want to perform? Add
? The URL to Git repository with the function source code: https://github.com/matzew/funcy-app
? The Git branch or tag we are targeting: main
? A subpath within the repository: 
? Do you want to configure webhook trigger? No
Error: "" is not a known builder. Available builders are "pack" and "s2i"
```

**Comment by lkingland** [comment]
It looks like the config prompt system is not using the config system fully, and is instead expecting the func.yaml to always include a value for this field.  The correct order of precedence, in ascending order, is 1) static default from code 2) global setting 3) function's existing value from a previous build 3) environment variable 4) flag.

This is a bug and will require an update of `func config`
