### ISSUE TITLE
lifecycle hook apis

### ISSUE THREAD

**Issue by matzew** [knative/func#1981]
Looking at the Go lang tempaltes, I am seeing some nice hooks to plug into the lifecycle of a function:
https://github.com/knative/func/blob/main/templates/go/.instanced-http/function.go#L34-L69

It would be nice if other SDKs/languages, such as `Node.js`, `quarkus` would have these APIs:
* `Start`
* `Stop`
* `Alive`
* `Ready`

Seems pretty handy

**Comment by matejvasek** [comment]
@matzew JS/TS have this too https://github.com/rh-max/openshift-docs/blob/a500f4874d3c0a14a88265d451ca1ea39d6fcd29/modules/serverless-nodejs-functions-overriding-liveness-readiness.adoc 

With Quarkus you can do it too albeit it might be little bit more complicated. You just need to use standard Java lifecycle thingies `@PostConstruct` `@PreDestroy`. For health probes check out https://quarkus.io/guides/smallrye-health.

**Comment by lkingland** [comment]
Yes, however we should probably leave this as an open issue because I think we should discuss how these are implemented and invoked to ensure we're being consistent.

**Comment by lkingland** [comment]
Adding lifecycle hooks to all runtimes is an ongoing effort and discussed in https://github.com/knative/func/discussions/2081
