### ISSUE TITLE
Build Error: Missing Required Mixin(s) libexpat1 in Paketo Buildpacks

### ISSUE THREAD

**Issue by helloxjade** [knative/func#1984]
Description:
I encountered an error while trying to build a function using func run --builder-image=registry.cnbita.com:5000/knative-releases/paketo-buildpacks/builder:base. The error states that the required mixin libexpat1 is missing.  registry.cnbita.com:5000/knative-releases/paketo-buildpacks/builder:base is equal to the gcr.io/paketo-buildpacks/builder:base

Logs:
`Error: failed to build the function: validating stack mixins: index.docker.io/paketobuildpacks/run:base-cnb missing required mixin(s): libexpat1
`

Environment:
OS:    CentOS Linux release 7.9.2009 (Core)
func CLI version:   v0.38.0-12-g0d6e2106
Docker version:   23.0.6

Steps to Reproduce:
Run the command func run --builder-image=registry.cnbita.com:5000/knative-releases/paketo-buildpacks/builder:base
Observe the error message.
Expected Outcome:
The function should build successfully.

Actual Outcome:
Received an error message about missing mixin(s) libexpat1.

Questions:
Why am I encountering this issue?
How can this issue be resolved?

**Comment by matejvasek** [comment]
What language did you try to compile?

**Comment by helloxjade** [comment]
> What language did you try to compile?
I tried to compile Go (or Golang) code

**Comment by matejvasek** [comment]
Where does `registry.cnbita.com:5000/knative-releases/paketo-buildpacks/builder:base` comes from? You should use `ghcr.io/knative/builder-jammy-base` with Func Go.

**Comment by matejvasek** [comment]
Oh wait actually latest released version still uses `gcr.io/paketo-buildpacks/builder:base`.

**Comment by matejvasek** [comment]
I have trouble to reproduce this.

**Comment by matejvasek** [comment]
Did you just `docker tag gcr.io/paketo-buildpacks/builder:base registry.cnbita.com:5000/knative-releases/paketo-buildpacks/builder:base` ? What is the digest of the image?

**Comment by matejvasek** [comment]
Maybe this was some temporary error that they already fixed?

**Comment by helloxjade** [comment]
> Did you just `docker tag gcr.io/paketo-buildpacks/builder:base registry.cnbita.com:5000/knative-releases/paketo-buildpacks/builder:base` ? What is the digest of the image?

yes .  I just do  `docker tag gcr.io/paketo-buildpacks/builder:base registry.cnbita.com:5000/knative-releases/paketo-buildpacks/builder:base`

**Comment by helloxjade** [comment]
> Maybe this was some temporary error that they already fixed?

"No, the error still exists, and I haven't found the reason for it yet."

**Comment by helloxjade** [comment]
"Is it possible to customize or configure the index.docker.io/paketobuildpacks/run:base-cnb image in Knative Func? I'd like to include specific libraries or mixins in the default build image, and I'm wondering if there's a way to achieve this through configuration or customization."

**Comment by matejvasek** [comment]
> "Is it possible to customize or configure the index.docker.io/paketobuildpacks/run:base-cnb image in Knative Func? I'd like to include specific libraries or mixins in the default build image, and I'm wondering if there's a way to achieve this through configuration or customization."

In is not configurable this way. However you can create your own builder image that refers your run images.

**Comment by matejvasek** [comment]
I was not able to reproduce this issue. When I just tagged `docker tag gcr.io/paketo-buildpacks/builder:base registry.cnbita.com:5000/knative-releases/paketo-buildpacks/builder:base` and run build it worked for me.

**Comment by matejvasek** [comment]
Is there anything special you are doing? What does you project looks like? What CLI options did you use?

**Comment by matejvasek** [comment]
What about using full builder: https://github.com/knative/func/pkgs/container/builder-jammy-full would it solve your problems?
