### ISSUE TITLE
Command to get version of `func` CLI

### ISSUE THREAD

**Issue by datho7561** [knative/func#2067]
How do I get information on the version of the `func` CLI that I'm using? `func version` doesn't report the client version, instead it reports what I think is the Knative function version on the cluster? `func version -v` reports the commit, which is helpful, but then I have to search the repo to figure out which release that corresponds to.

**Comment by mwmahlberg** [comment]
@datho7561 You might want to give `func environment` a shot. This gives you quite some information and then some.

However, your premise of `func version` returning the Knative version is incorrect:

<img width="1039" alt="Bildschirmfoto 2023-11-10 um 23 32 36" src="https://github.com/knative/func/assets/138420/24d18711-2c40-4b77-b64a-5960b7ed95ec">

hth

**Comment by lkingland** [comment]
Yes, `func version` is reporting the version of the CLI that you're running.  Functions doesn't require anything installed in the cluster other than Knative (Serving and Eventing).

We aren't (yet) tagging the CLI releases regularly, so the version is how far ahead the CLI you're running is from the last tagged version.  In your first case, you're running the Functions CLI which is 99 commits ahead of the last tagged release, `0.38.0`, which is commit `gcd0bc6ae`.

I hope that helps; we are actively working on improving our release process 👍🏻

**Comment by lkingland** [comment]
Please feel free to reopen or file another issue (or discussion) with more questions

**Comment by datho7561** [comment]
I'm sorry, I think I misunderstand something. When I run `func version` with version `1.12.0` it reports the version as `v0.38.0-99-gcd0bc6ae`. Is there a way to get `func version` to report `1.12.0`?
