### ISSUE TITLE
About the path of files

### ISSUE THREAD

**Issue by villinale** [knative/func#2096]
Hi, there!

I want to use my own files in the func.py.
Will all files in the function folder be uploaded to the image? If so, what is the path for these files?

Thanks for your help.

**Comment by matejvasek** [comment]
I believe most of files in project directory should be uploaded with exception of those that are explicitly ignored.

**Comment by lkingland** [comment]
I believe Matej answered your question. Please reopen if you still need assistance. 

The way to exclude files is using the .funcignore file. Other files should be accessible by the running Function.
