### ISSUE TITLE
Change client.go's `subscription` to better reflect the Trigger Filter attributes

### ISSUE THREAD

**Issue by matzew** [knative/func#2122]
Currently the `client.go` file contains a `Subscription`:
```go
type Subscription struct {
	Source string `json:"source" yaml:"source"`
	Type   string `json:"type" yaml:"type"`
	Broker string `json:"broker" yaml:"broker"`
}
```
This `struct` is wrong, since it _only_ represents the `source` and/or `type` attributes on the `Trigger.Filter`, however that can be anything, no requirement on `source` or `type` as a criteria.

**Comment by matzew** [comment]
See also https://github.com/knative/eventing/issues/7265

**Comment by matzew** [comment]
It would be nice, if for `func describe` things would render like:

```
Subscriptions (Broker and Attributes):
  my-broker, map[source:/something type:org.apache.camel.event.aws.s3.getObject extension:someOther]
```

**Comment by Shubham-Rasal** [comment]
Current `func describe` output looks like this 

```bash
Function name:
  sentiment-analysis-app
Function is built in image:
  
Function is deployed in namespace:
  default
Routes:
  http://sentiment-analysis-app.default.127.0.0.1.sslip.io
```

Do you suggest adding a new field for Subscriptions?
