### ISSUE TITLE
GSoC idea: WASM support to Knative Functions

### ISSUE THREAD

**Issue by matzew** [knative/func#2151]
In the past we have explored the idea to add support for `WASM`. 

The most relevant discussion we had is listed here:
https://github.com/knative/func/discussions/1489

For Google Summer of Code 2024 it would be nice to have this as an application for a project idea.

```
- Description: Wasm aka WebAssembly provides a portable binary-code format that is ideal to write small functions. However, current support for Wasm in Knative Functions is limited and slow. This project will improve this support.
- Expected Outcome: Contribute Wasm support to Knative functions, documentation, sample code etc. Ideal outcome would be running Wasm code via Knative Functions in a convenient way. However, there are some unknowns. Other possible outcome could be identifying the roadblocks and possible improvements
- Recommended Skills: basic programming skills, use IDE and debugger, some experience with Kubernetes
- Expected project size: medium (~175 hour project)
- Mentor(s):
  - @aslom
  - @matzew
  - @lkingland
```

**Comment by pandeyshubham03** [comment]
Hello @matzew, I'm interested to work on this idea for GSOC 2024. Can you provide me any resources where I can get started. Also, is there any slack link for the same?

**Comment by aayanmtn** [comment]
Hello @matzew @aslom @lkingland  I am crazy about the CNCF project for now I feel this one is the most suitable one for me according to my skill set. Could you guide me further on 'How to start?'?

**Comment by prashant235913** [comment]
I am interested in this project.....Will keep updating people what I'll learn for solving this

**Comment by sayantani11** [comment]
Interested in contributing!

**Comment by rakeshrocky58008** [comment]
hi @matzew I am interested in contributing!

**Comment by Harshal-Rembhotkar** [comment]
Hello @matzew @aslom @lkingland mentors i am Harshal Rembhotkar , 4th semester Engineering(Automobile) student, i excited to join your organization ,my tech stacks are Java , html, css ,version control system, springboot framework ,mysql DB  and technologies that i learned are like docker ,kubernetes and i also i have little idea about other  Devops tools. i am selected this project for GSOC '24.
Thanks !!

**Comment by lkingland** [comment]
Just a reminder that proposals can be sumitted via the web form here: https://summerofcode.withgoogle.com/programs/2024/organizations/cncf

**Comment by lkingland** [comment]
This GSoC project completed successfully.
Unfortunately we decided the WASM runtime's available APIs are currently not quite rich enough to provide adequate request handling to the resident Function.
We expect to revisit the project in the future.
