### ISSUE TITLE
`builderImages` is ignored

### ISSUE THREAD

**Issue by braunsonm** [knative/func#2183]
`builderImages` configuration in `func.yaml` is documented here: https://github.com/knative/func/blob/main/docs/reference/func_yaml.md#builderimages

However, no matter the value placed in this configuration, the `builderImages.pack` is ignored by both the `func build` and `func deploy` commands.

## Reproduction

1. Create any func project `func create --language springboot myfunc`
2. Change `func.yaml` to contain
```yaml
builderImages:
  pack: paketobuildpacks/builder-jammy-full:latest
```
3. `func build` - notice it still uses `ghcr.io/knative/builder-jammy-base:latest`

**Comment by matejvasek** [comment]
The doc seems to be outdated.
The `builderImages` option should be under `build` section.
```yaml
build:
  builderImages:
    pack: paketobuildpacks/builder-jammy-full:latest
```

**Comment by braunsonm** [comment]
I can confirm that works @matejvasek 
I'll leave this issue open as the documentation needs to be updated.
