### ISSUE TITLE
Support GitOps with an option to output as YAML

### ISSUE THREAD

**Issue by braunsonm** [knative/func#2192]
Right now in order to deploy a function you need to run `func deploy` on a machine that is configured with access to your Kubernetes cluster.

In a GitOps approach, `func deploy` would have a parameter to output the generated Knative Service CR as YAML for example `func deploy --build false -o yaml > knative-service.yml`. This would allow GitOps tools like ArgoCD and Flux to read this committed YAML document in the source repository.

**Comment by lkingland** [comment]
Yes, exporting a `.yaml` is on our roadmap.  If you don't want CI to have cluster access, you can use `func build`  to update a container, and then define your service directly with `service.yaml` checked into source control

**Comment by khusseini** [comment]
@lkingland does a function consist of basically only the service definition or are there any other CRDs created?
