### ISSUE TITLE
Adding ca certificates to support transparent proxy

### ISSUE THREAD

**Issue by d-m** [knative/func#2193]
Hello, is it possible to add a CA certificate to be used during func build steps? I’m working with a transparent proxy and builds using buildpacks fail when downloading versions of Python, go, etc. in the container. This seems to be possible with with the build pack “pack” command using bindings but I wasn’t sure if this was exposed in func. Thanks!

**Comment by braunsonm** [comment]
This is not supported in func, see: https://github.com/knative/func/issues/2177

**Comment by matejvasek** [comment]
It should work: https://cloud-native.slack.com/archives/C04LKEZUXEE/p1707837008531269 .

**Comment by Vishal1297** [comment]
> @d-m try putting your CAs in your project directory and stetting the `SSL_CERT_DIR` envvar.
> 
> ```yaml
> build:
>   buildEnvs:
>     - name: SSL_CERT_DIR
>       value: /workspace
> ```

What should be value for **SSL_CERT_DIR** in windows and linux?
Is this common for all environments?

**Comment by matejvasek** [comment]
@Vishal1297 it should be just `/workspace` -- that's the path of source code in a build container.

**Comment by Vishal1297** [comment]
@matejvasek Thanks, It worked but now I am facing another issue.
Error is there while downloading go modules from private repo.

[Server certification verification failed](https://stackoverflow.com/questions/21181231/server-certificate-verification-failed-cafile-etc-ssl-certs-ca-certificates-c)

Maybe my certs having correct?

**Comment by Ruanjq98** [comment]
> @d-m try putting your CAs in your project directory and stetting the `SSL_CERT_DIR` envvar.
> 
> ```yaml
> build:
>   buildEnvs:
>     - name: SSL_CERT_DIR
>       value: /workspace
> ```

Is this configuration item written in func.yum?

**Comment by Vishal1297** [comment]
> @matejvasek Thanks, It worked but now I am facing another issue. Error is there while downloading go modules from private repo.
> 
> [Server certification verification failed](https://stackoverflow.com/questions/21181231/server-certificate-verification-failed-cafile-etc-ssl-certs-ca-certificates-c)
> 
> Maybe my certs having correct?

It's resolved with help of `go mod vendor`

**Comment by matejvasek** [comment]
> @matejvasek Thanks, It worked but now I am facing another issue. Error is there while downloading go modules from private repo.
> 
> [Server certification verification failed](https://stackoverflow.com/questions/21181231/server-certificate-verification-failed-cafile-etc-ssl-certs-ca-certificates-c)
> 
> Maybe my certs having correct?

Hard to tell without more output. Maybe `go` does not respect `SSL_CERT_DIR`, I do not know.

**Comment by Vishal1297** [comment]
> > @matejvasek Thanks, It worked but now I am facing another issue. Error is there while downloading go modules from private repo.
> > [Server certification verification failed](https://stackoverflow.com/questions/21181231/server-certificate-verification-failed-cafile-etc-ssl-certs-ca-certificates-c)
> > Maybe my certs having correct?
> 
> Hard to tell without more output. Maybe `go` does not respect `SSL_CERT_DIR`, I do not know.

`SSL_CERT_DIR` env works with https://github.com/paketo-buildpacks/go
What I got to know is that we have two options to solve the certificate problem.

- [paketo-buildpacks/go-mod-vendor](https://github.com/paketo-buildpacks/go-mod-vendor)
- Git bindings

**Comment by matejvasek** [comment]
What are "Git bindings"?

**Comment by Vishal1297** [comment]
> What are "Git bindings"?

I mean bindings for git [paketo.io/docs/howto/configuration/#bindings](https://paketo.io/docs/howto/configuration/#bindings).
Not sure how to use it.

**Comment by lkingland** [comment]
See @matejvasek solution above, which should work in most cases for the question from the OP:

@d-m try putting your CAs in your project directory and stetting the `SSL_CERT_DIR` envvar.
```yaml
build:
  buildEnvs:
    - name: SSL_CERT_DIR
      value: /workspace
```
