### ISSUE TITLE
`func version` does not match release version

### ISSUE THREAD

**Issue by drriguz** [knative/func#2252]
Hi,

the github releases is tagged as 1.13 or 1.12, however  `func version` shows another version number:

```
$ func version
v0.40.1
```

Is this a bug?

**Comment by lkingland** [comment]
Func version shows the version of the Function Go library directly, whereas the github release is tagged to match the Knative version it is bundled with.  Try running it with verbose mode `func version -v`.

Yes, we are aware this can be confusing and are considering different options to make the difference more clear.
