### ISSUE TITLE
CORS support

### ISSUE THREAD

**Issue by drriguz** [knative/func#2259]
Hi,
I'm accessing knative functions in browser and got CORS issue. How can we add CORS policy to the function?

And I'm using go and cloud event:

```go
func Handle(ctx context.Context, event cloudevents.Event) (resp *cloudevents.Event, err error)
```

Thanks!

**Comment by lkingland** [comment]
This is a question about how the CloudEvents API itself works, because Functions simply passes through the events.

I would presume that you `import cehttp "github.com/cloudevents/sdk-go/v2/protocol/http"` and then add a header to the context
```
	header := http.Header{}
	header.Set("Access-Control-Allow-Origin", "*")
	cehttp.WithCustomHeader(ctx, header)
```
I haven't tried this, and would be curious to know if it works!

**Comment by drriguz** [comment]
unfortunately it does not work, because `cehttp.WithCustomHeader(ctx, header)` won't change the original context but returns a new context instead. However there's no suitable function signature to allow users to change context, context is passed by value:

**Comment by matejvasek** [comment]
@drriguz for finer control you could use signature: `func Handle(w http.ResponseWriter, r *http.Request)`.

And then use cloud event SDK to manipulate cloud events.
```go
package function

import (
	"context"
	"net/http"

	cloudevents "github.com/cloudevents/sdk-go/v2"
	cebinding "github.com/cloudevents/sdk-go/v2/binding"
	cehttp "github.com/cloudevents/sdk-go/v2/protocol/http"
)

func Handle(w http.ResponseWriter, r *http.Request) {
	event, err := cehttp.NewEventFromHTTPRequest(r)
	if err != nil {
		panic(err)
	}

	w.Header().Add("Access-Control-Allow-Origin", "*")
	
	err = cehttp.WriteResponseWriter(r.Context(), (*cebinding.EventMessage)(event), 200, w)
	if err != nil {
		panic(err)
	}

}
```

**Comment by drriguz** [comment]
> @drriguz for finer control you could use signature: `func Handle(w http.ResponseWriter, r *http.Request)`.
> 
> And then use cloud event SDK to manipulate cloud events.
> 
> ```go
> package function
> 
> import (
> 	"context"
> 	"net/http"
> 
> 	cloudevents "github.com/cloudevents/sdk-go/v2"
> 	cebinding "github.com/cloudevents/sdk-go/v2/binding"
> 	cehttp "github.com/cloudevents/sdk-go/v2/protocol/http"
> )
> 
> func Handle(w http.ResponseWriter, r *http.Request) {
> 	event, err := cehttp.NewEventFromHTTPRequest(r)
> 	if err != nil {
> 		panic(err)
> 	}
> 
> 	w.Header().Add("Access-Control-Allow-Origin", "*")
> 	
> 	err = cehttp.WriteResponseWriter(r.Context(), (*cebinding.EventMessage)(event), 200, w)
> 	if err != nil {
> 		panic(err)
> 	}
> 
> }
> ```

Yes, it works. I'm using the following code:

```go
func Handle(ctx context.Context, res http.ResponseWriter, req *http.Request) {
	res.Header().Set("Access-Control-Allow-Origin", "*")
	res.Header().Set("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS")
	res.Header().Set("Access-Control-Allow-Headers", "Content-Type, Authorization")
	if req.Method == "OPTIONS" {
		res.WriteHeader(http.StatusOK)
		return
	}
	// ....
        
	res.Header().Set("Content-Type", "application/json")
	res.WriteHeader(http.StatusOK)
	res.Write(jsonData)
}
```
