### ISSUE TITLE
How to use func deploy --remote in air gapped environment ?

### ISSUE THREAD

**Issue by nmatsukiyo** [knative/func#2275]
I was trying to use the `func deploy --remote` to do a build and deploy using tekton on local cluster and encountered the following error.

```sh
$ func deploy --remote --registry registry.local/function
Creating Pipeline resourcesError: failed to run pipeline: problem creating pipeline: Get "https://raw.githubusercontent.com/knative/func/release-1.13/pkg/pipelines/resources/tekton/task/func-buildpacks/0.2/func-buildpacks.yaml": dial tcp 185.199.110.133:443: i/o timeout
```

My environment is in an air gap environment and I can't go outside using Web Proxy.

Is there any way to avoid this by setting the func command, etc.?

**Comment by matejvasek** [comment]
I am sorry for the complication. We are planning to embed theses resources directly into func binary soon.

In meantime you could host these resource somewhere where it is reachable for you and then compile func that refenreces these resources. You will need changes urls here: https://github.com/knative/func/blob/7e95ca21817b878ae4bc69ad849965c41cda6059/pkg/pipelines/tekton/templates.go#L94-L98

**Comment by nmatsukiyo** [comment]
I understand that I just need to change the URL and build it.

Thanks for the advice.
