### ISSUE TITLE
Bug: Wrong error message when running func commands if the function is not initialized

### ISSUE THREAD

**Issue by Leo6Leo** [knative/func#2280]
**Issue Summary:**

When executing the commands `func deploy`, `func run`, and `func build` without first initializing a function (missing `func.yaml` file due to not running `func create` or `func init`), the error handling leads to an unclear message. This occurs even if the commands are typed correctly.

**Current Behavior:**

Attempting to run any of the above commands without initializing a function results in a misleading error message related to registry validation:

```
func build -b=s2i -v
A registry for function images is required. For example, 'docker.io/tigerteam'.
X Sorry, your reply was invalid: invalid registry ["quay.io/user-abc"]: name required
? Registry for function images:
```
The error message should clearly indicate that the function has not been initialized and provide guidance on the necessary steps to proceed.

**Proposed Solution:**

Improve the error message to more accurately reflect the issue and guide the user. Suggested new error message:

```
Error: No function has been initialized in the current directory ({path}). Please initialize a function by running either:
- func init --language <your language>
- func create <function name> --language <language>
```

**Comment by lkingland** [comment]
Thanks @Leo6Leo,

This does look like a logic problem.  There should be a different error there.

I've added this to the roadmap

**Comment by EraKin575** [comment]
I would like to work on this issue!

**Comment by gauron99** [comment]
@EraKin575 hello, are you still working on this issue?

**Comment by tarunsunny3** [comment]
I want to work on this issue, if no one else is interested anymore

**Comment by gauron99** [comment]
@tarunsunny3 great! have a go and if you have questions, feel free to ask

**Comment by tarunsunny3** [comment]
Hi @gauron99 
This is my second OSS contrubution(1st one was just a README update)

I forked the repo and started working on it and was going over the cmd/ folder and mostly where the changes need to be made

But before doing anything else, I wanted to run '**make**' and see it and other commands(make check, etc) run properly

But it is throwing errors as shown below
![image](https://github.com/user-attachments/assets/303522cd-2ca8-475a-8230-319d3015ae67)
I tried to debug, and ran git tag to see that it's giving empty output for VTAG, even after pulling the tags from the original repo, still VTAG seems to be empty and in Makefile we have the code where if VTAG is empty it's defaulting to ETAG, but ETAG was nowhere defined
![image](https://github.com/user-attachments/assets/cbb0722c-0597-4131-8f19-d7ef13d1ebd0)

Can you please share any beginner resources or a community to join?

Thanks!

**Comment by gauron99** [comment]
> Can you please share any beginner resources or a community to join?

sure, here is a CNCF slack `knative-functions` community
https://cloud-native.slack.com/archives/C04LKEZUXEE

as of other resources: we have [docs](https://knative.dev/docs/functions/) for now.
(We are actually working on function templates and "better docs" as of right now and they are not done yet - sorry for that)

There is also [knative quickstart](https://knative.dev/docs/getting-started/) that will walk you through the creation of the function, its building/deployment and you can take a look at other parts of knative if thats something that interests you.

sidenote: Im sorry I have not seen your error before, so cant provide quick fix. I will take a look and let you know if I find something helpful.

**Comment by lkingland** [comment]
I do not believe this has to do with VTAG, but rather the value of LDFLAGS appears to be incorrect.

Can you please post the output of `make -version`?

**Comment by tarunsunny3** [comment]
I joined the Slack community, and got help from there
@matejvasek helped me
It was because I had an older version of Go, I updated it to 1.22 and it worked fine

Thanks!

**Comment by tarunsunny3** [comment]
I've made changes only to build.go, so that we can discuss if this okay
