### ISSUE TITLE
Func-go buildpack sources

### ISSUE THREAD

**Issue by appiepollo14** [knative/func#2329]
Hi There,

Love to see the underlying code of the Func-go buildpack. Would like to understand how the go sources, without a main class, are compiled to what should be a working function. I ask this as I can't find the buildpack sources / repo.

Kind regards

**Comment by matejvasek** [comment]
Right now this is used: https://github.com/boson-project/packs/tree/main/buildpacks/go 
However this will change soon.

**Comment by appiepollo14** [comment]
@matejvasek Thanks for your early reply. This is the info I was looking for. What is the change you're referencing?
