### ISSUE TITLE
Go function does not build

### ISSUE THREAD

**Issue by appiepollo14** [knative/func#2330]
Hi there,

I'am not able to build a Go function. I create a function using the cli: `func create -l go hello-world`. After which I use the cli to execute: `func build` which then fails with the error: `go: no main packages to build`

How to solve?

**Comment by matejvasek** [comment]
cc @lkingland

**Comment by lkingland** [comment]
Hello @appiepollo14,

I am unable to recreate the issue you are seeing.  Can you please run `func version --verbose` and show the exact commands that you are running (with anything sensitive redacted of course).

**Comment by appiepollo14** [comment]
I will once I'm back from holiday in a week or so.

**Comment by appiepollo14** [comment]
@lkingland Weirdest thing ever, I didn't do anything different nor update anything, but now the function builds without the error mentioned above. 

For completeness: here is the result of `func version --verbose`

```
Version: v0.40.0
Knative: =v1.13.0
Commit: a700b89b
SocatImage: quay.io/boson/alpine-socat:1.7.4.3-r1-non-root
TarImage: quay.io/boson/alpine-socat:1.7.4.3-r1-non-root
```
The steps I execute:

1. func create -l go hi
2. cd hi
3. func build
