### ISSUE TITLE
Namespace issues on delete?

### ISSUE THREAD

**Issue by matzew** [knative/func#2364]
Looks like with the recent changes to `namespace`, there are issue?

```
Error: deploy error. timeout: service 's3-logger' not ready after 120 seconds
➜  s3-logger $GOPATH/src/knative.dev/func/func delete          
Error: namespace required
```

This was working before (I build `func` from `HEAD`).

**Comment by matzew** [comment]
CC @jrangelramos @lkingland

**Comment by lkingland** [comment]
This is almost surely related to the large namespace update we performed about that time.
We have E2E tests which now check.
I will assume this is no longer an issue, but please re-open if still occurring with your more recent tests.
