### ISSUE TITLE
Trying to validate Native 'tweaked' install on Rancher Desktop K8s (v1.29.5stable) on  Mac M1: functions deploy fails

### ISSUE THREAD

**Issue by stevef1uk** [knative/func#2375]
I have manually deployed Istio & Native on my local cluster as the automated script did not work. All pods seem to be running & I was able to deploy ok a sample istio application.

I had to manually edit some Knative yaml files to change V1beta1 to v1alpha1 to get the yaml files (serving-core.yam & serving-crds.yaml)  to deploy successfully so I am not sure of the state our my installation. I am actually trying to test Kserve which requires the above.

I have used the func command to create a go example and built it locally ok. When I try to deploy I am getting the following errors:
```
Error: deploy error. knative deployer failed to deploy the Knative Service: admission webhook "validation.webhook.serving.knative.dev" denied the request: validation failed: must not set the field(s): spec.template.spec.containers[0].securityContext.allowPrivilegeEscalation, spec.template.spec.containers[0].securityContext.seccompProfile
```

I tried Googling and couldn't find anything on this issue.  I adding the work arounds I used to use on Openshift without success:
```
oc adm policy add-scc-to-user anyuid -z default -n  knative-serving 
oc adm policy add-scc-to-user anyuid -z default -n kserve-test 
```
Any thoughts would be appreciated.

**Comment by lkingland** [comment]
This is probably due to an out-of-date Knative installation or `func` binary.  Try restarting your cluster with the latest Knative installation links from knative.dev, and the latest func binary from our releases, and please reopen this issue if you still see the error.
