### ISSUE TITLE
It would be nice to support docker buildx

### ISSUE THREAD

**Issue by stevef1uk** [knative/func#2380]
I am trying to create a function and deploy it to a Kind cluster running on a M2 Pro Mac.

The image is never downloaded from my docker hub repo because it hasn't been built with arm support.

The current functionality seems restricted just to X86 machines.

**Comment by matejvasek** [comment]
Try s2i builder `--builder=s2i`.

**Comment by lkingland** [comment]
> Try s2i builder `--builder=s2i`.

For Go and Python, you can use `--build
