### ISSUE TITLE
Improve the getting started docs

### ISSUE THREAD

**Issue by jcrossley3** [knative/func#335]
I don't think the getting started tutorial goes far enough. Ideally, there'd be a clear, concise description of how to trigger the function from a VERY SIMPLE event source.

The user shouldn't be required to spend any brain cycles understanding the domain of some pre-existing, sophisticated example, e.g. an image processing pipeline is cool, but i don't care about processing images. Essentially, I already have an event source in mind, but I know nothing of knative: can you show me a minimal yaml file that I can use as a template to tie _my_ source to _my_ function?

It may not be possible without first improving the knative-eventing docs, but even a link to what's currently there would be an improvement. `curl` is handy, but insufficient for getting started with functions.

**Comment by lance** [comment]
@jcrossley3 if you would like to contribute thoughts or review existing work that is attempting to address this issue, please do! https://github.com/boson-project/func/pull/332
