### ISSUE TITLE
Ease usage of private docker repository

### ISSUE THREAD

**Issue by matejvasek** [knative/func#497]
In order to use private repository like quay.io user has to set secrets to cluster I wish there was some easier way.

**Comment by jrangelramos** [comment]
I think this can be configured directly on the cluster, for example on Openshift we can "teach" the cluster how to pull from private repos using secrets.

**Comment by matejvasek** [comment]
@jrangelramos yes that's true, but we don't make easy for user, if user forgets to set the secret on the cluster then deployment fails and use has to search for the cause.

**Comment by matejvasek** [comment]
I updated description and title.

**Comment by shinigambit** [comment]
@matejvasek I wonder if you have any ideas in mind on how the usage of this would be. I was thinking:
- A new command in `func` like maybe `func config-registry`
- A flag in `func deploy` that would create/update and configure the pull secrets in the cluster
- A dynamic check at deploy time that detects that the pod's status is ImagePullBackoff and suggests the preferred way of configuring the secrets

There's probably more ways to achieve this but I'd like to know your thoughts.
Also I can see this being useful not only for functions. Maybe it's worth moving this to `kn` client?

**Comment by matejvasek** [comment]
I don't have specific idea. For starer just some check that image is private and subsequent warning with link to documentation should be enough.

**Comment by shinigambit** [comment]
Thanks @matejvasek , I think I can tackle this one.
/assign
