### ISSUE TITLE
`func create` command should default to confirm prompt

### ISSUE THREAD

**Issue by nainaz** [knative/func#573]
# Context
During User interviews. When users are creating functions, default choice of language wasn't the expected experience and confused them to think that Node is the only choice and doesn't let the user know that there are other choices available for language/runtime and/or templates. In addition, user had to consult the Help text multiple times and it resulted in disjointed experience.

# Story 

**As Deandra the Developer**
**I want** to understand what options are available to me when creating a new function
**So that** I become familiar with all of the options that func supports

# Acceptance Criteria

- [ ] Guide the user through all the options available while creating func project 
```
GIVEN I typed func create into my terminal 
WHEN I hit enter 
THEN I am guided by an interactive CLI (which currently requires -c flag) 
```

**Comment by omerbensaadon** [comment]
@nainaz I'm going to change this to default to -c the first time the user runs func create. 

I will open another issues which asks the user if they would like to store their option as their default runtime... 

Thoughts on this? @lance @lkingland @zroubalik where could this default be stored?

**Comment by lance** [comment]
@omerbensaadon we have a `func config` command that we have discussed adding things like this to. Currently `func config` affects only the local project, but the tentative plan is to have `func config global` to manage global configuration options such as this (or possibly `func config -g`.

Already, we store installed remote template repositories that have been added with `func repo add` in `~/.config/func/repositories`. Global configuration such as the default runtime to use on create will be stored in a configuration file in `~/.config/func/config.yaml` or similar.

**Comment by lkingland** [comment]
I am pretty sure the core problem here:
> default choice of language wasn't the expected experience
Will be solved by implementing the git-like behavior of prompting a user to provide the `--language` flag, but informing them this can be defaulted for future invocations using `git config X --local`.
This might make changing the default behavior to the `-c` flow unnecessary, but we can take a look again at that time!

**Comment by lance** [comment]
@nainaz there are a couple of overlapping issues related to this. I closed one AND created one of them yesterday. :stuck_out_tongue: 

https://github.com/knative-sandbox/kn-plugin-func/issues/768 was created in favor of https://github.com/knative-sandbox/kn-plugin-func/issues/635, which I closed. And I think we should consider closing this one as well. wdyt?

**Comment by omerbensaadon** [comment]
Glad y'all are finally getting around to some of this stuff!! 

I think this one is actually quite important for onboarding new users. IMO, we want to keep devs "hacking" for as long as possible before they have to reference any documentation. 

This feature (combined with #768) would make it so users wouldn't need to know anything but "func create" in their first experience.

**Comment by lance** [comment]
To be clear... If a user types `func create` with no flags or other parameters, the default should be to enter `confirm` mode as though they had typed `func create -c`. But anything other than a bare `func create` should behave as it does today?

For example for the two scenarios below are behaving as desired today.

```
❯ kn-func create -t events
Error: Required flag "language" not set.
Available language runtimes are:
  go
  node
  nodejs
  python
  quarkus
  ruby
  rust
  springboot
  typescript
```
And 
```
❯ kn-func create -l node
Created node Function in /home/lanceball/src/github.com/boson-project/buildpacks/foo
```

I like this - makes sense. Apologies for not fully grasping the ask earlier.

**Comment by nainaz** [comment]
Yes.
That is the ask :)
No worries.
Thank you,
-N

**Comment by lance** [comment]
This can be deferred to post 1.0

**Comment by nainaz** [comment]
I agree that cluster build, global configuration and s2i are more important feature. 
I would still like this "mistake" from users turned into experience. 
If we all think that it is "nice to have" I will stop pushing.  :)  :)

**Comment by nainaz** [comment]
@Mauricio Salatino ***@***.***> adding you to the issue that is
around create command for putting this as reference on new issue.
Thank you,
-N

**Comment by lance** [comment]
Should be resolved in https://github.com/knative-sandbox/kn-plugin-func/issues/901

**Comment by grafvonb** [comment]
@lkingland Are you working on it? If not, I can take over.

**Comment by lkingland** [comment]
> @lkingland Are you working on it? If not, I can take over.

Yes
