### ISSUE TITLE
Dynamic Templates

### ISSUE THREAD

**Issue by omerbensaadon** [knative/func#619]

**Comment by nainaz** [comment]
@matejvasek, please fill in the details and link to feature track.

**Comment by matejvasek** [comment]
spec is being disused here: https://github.com/matejvasek/func-dynamic-templates/pull/1

**Comment by lance** [comment]
/kind needs-validation
Need also a valid design and plan

**Comment by lance** [comment]
https://github.com/matejvasek/func-dynamic-templates/pull/1
