### ISSUE TITLE
(VMware) Upstreaming Python + Springboot Buildpacks: https://github.com/vmware-tanzu/function-buildpacks-for-knative

### ISSUE THREAD

**Issue by omerbensaadon** [knative/func#634]

**Comment by lance** [comment]
@evankanderson I've reopened this, since it got overly stale and was closed. If you and/or @salaboy think it's not needed, feel free to close again.

**Comment by lance** [comment]
@salaboy it's not clear to me what vmware plans are, but based on the conversation in last WG meeting, my sense is that this should be closed.

**Comment by evankanderson** [comment]
I _think_ VMware is taking responsibility for maintaining these, so if it doesn't cause additional friction with the community to keep them in their current place, I don't know that we need to move them.

**Comment by lance** [comment]
@evankanderson OK I will close the issue. Of course, we can open a new one if things change.
