### ISSUE TITLE
`func create`: persist --language choice

### ISSUE THREAD

**Issue by omerbensaadon** [knative/func#636]
- Give users the option to save the runtime as default (y/n) 
- Make sure to let them know where this is saved
- Make sure the template always defaults to -c when not provided as a flag (-t)

**Comment by lance** [comment]
> * Make sure to let them know where this is saved

I don't think that's a great idea. I think the user should just be able to run `func config global`. See: https://github.com/knative-sandbox/kn-plugin-func/issues/573#issuecomment-962003540

**Comment by lkingland** [comment]
I will discuss this further with @lance this week, but the work I am doing on `func invoke` actually requires taking a bite out of the `config` situation:  in particular opening the door to more conventional "config" settings, including git-like behavior of displaying a helpful message informing the user they need to choose a language, but can set a default via `git config ... --global`  (exact syntax TBD)

**Comment by lkingland** [comment]
To expand on this issue a bit, I was envisioning that the first time `func` is run, it will detect there is no user configuration, and the user will be prompted to run through a first-time setup, which is creating the global config (see #901).   One of the questions asked of course being the user's preferred default language (if any).
