### ISSUE TITLE
[Docs/Specs] Template detection specification

### ISSUE THREAD

**Issue by dolfolife** [knative/func#673]
_**Note**: this might not be the right repo for this issue but I can move if this https://github.com/knative-sandbox/kn-plugin-func/discussions/662 resolves._

## Description

Buildpacks today use different mechanisms for detecting the function code. One common trigger is the presence of the file `func.yaml`, and other buildpacks rely on the use of Environment variables set while they build the source code.

Templates should come with the basic structure to build and deploy functions locally and other methods. We should extend our template guide to provide the approach which buildpacks are going to detect, and work together to provide the same experience across buildpacks.

## Location

- https://github.com/knative-sandbox/kn-plugin-func/blob/main/docs/guides/templates.md#language-packs

## Additional Context

- The CLI also provides the option for external repositories and we want to make sure these templates can be built using the same mechanism as other buildpacks.
- Our conversation around on-cluster builds also suggest we want to build flexibility around how functions are detected. [Source of the experiment](https://github.com/salaboy/func-oncluster-build-experiments)

**Comment by nainaz** [comment]
https://github.com/boson-project/packs/pull/4

**Comment by nainaz** [comment]
https://github.com/vmware-tanzu/function-buildpacks-for-knative/blob/main/buildpacks/python/python/detect.go#L27

**Comment by salaboy** [comment]
I am closing this because I don't think we will be changing this soon, the detection mechanism today is based on having the `func.yaml` file. If we have a different proposal, or if we want to bring a new proposal for detection we should do so in a separate issue.
