### ISSUE TITLE
On-cluster build: allow pipeline override or pipeline export for a func project

### ISSUE THREAD

**Issue by salaboy** [knative/func#791]
Currently, pipelines are defined inside the CLI and cannot be overridden. allowing to export the pipeline into a YAML file that can be updated and replaced on the cluster for that specific function project will enable other tasks to be performed as part of the function deploy or build process.

**Comment by shinigambit** [comment]
@zroubalik you mean like changing the pipeline flag from bool to be the path to the with the pipeline definition?
