### ISSUE TITLE
On-cluster build: Implement interactive prompt

### ISSUE THREAD

**Issue by lance** [knative/func#852]
Currently, on-cluster builds are accomplished through the `func deploy` command. While there is a `--confirm` prompt for local builds it does not account for the possibility that the user would like to build on the cluster, and therefore does not prompt for that information. See:

![image](https://user-images.githubusercontent.com/15952/190496283-9fb6a1b3-76f4-4f55-9402-fb6452b1c5dd.png)

The `--confirm` mode should start by asking the user if they would like to build locally or on the cluster and proceed from there.

**Comment by lance** [comment]
I started hacking around to do this in `func config`, but it’s odd because it’s not exactly like the others where you can add/remove items. Instead, you just provide new or updated values (or remove them). But the “add” terminology seems not exactly right. And “list” is OK, but I’d prefer “display”.

**Comment by lance** [comment]
@vyasgun hi! Any updates on this?

**Comment by vyasgun** [comment]
@lance working on it
