### ISSUE TITLE
On-cluster build: Validate all Git options

### ISSUE THREAD

**Issue by lance** [knative/func#857]
We should validate all options for `git`(`gitUrl`,`contextDir`, `revision`...), there are two scenarios:

1. if `build: git` is specified in `func.yaml`.
2. if `build` in `func.yaml` is not set to `git`, but `-b git` is specifed as a parameter for `func build|deploy`

Currently there is a problem if `build: local` is set in `func.yaml` and `-b git` is specified as a parameter and `gitUrl` is not set:

```bash
./func deploy -p test-func-b git 
🕛 Creating Pipeline resources
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x27eee7d]

goroutine 1 [running]:
knative.dev/kn-plugin-func/pipelines/tekton.generatePipeline({{0xc0005a0fa8, 0x6}, {0x7ff7bfeff5f1, 0x11}, {0xc0001292a8, 0x11}, {0x0, 0x0}, {0xc0005a0fd8, 0x2}, ...}, ...)
        /Users/zroubali/go/src/knative.dev/kn-plugin-func/pipelines/tekton/resources.go:40 +0x11d
knative.dev/kn-plugin-func/pipelines/tekton.(*PipelinesProvider).Run(_, {_, _}, {{0xc0005a0fa8, 0x6}, {0x7ff7bfeff5f1, 0x11}, {0xc0001292a8, 0x11}, {0x0, ...}, ...})
        /Users/zroubali/go/src/knative.dev/kn-plugin-func/pipelines/tekton/pipeplines_provider.go:94 +0x305
knative.dev/kn-plugin-func.(*Client).RunPipeline(0xc0005ad800, {0x30db938?, 0xc0009b1180}, {0x7ff7bfeff5f1, 0x11}, {0x0?, 0x0?, 0x0?})
        /Users/zroubali/go/src/knative.dev/kn-plugin-func/client.go:709 +0x271
knative.dev/kn-plugin-func/cmd.runDeploy(0xc0008b8a00, {0xc000c3fcb8?, 0xc000c3fc90?, 0x0?}, 0x2e80008)
        /Users/zroubali/go/src/knative.dev/kn-plugin-func/cmd/deploy.go:189 +0xbac
knative.dev/kn-plugin-func/cmd.NewDeployCmd.func1(0xc0008b8a00?, {0xc000b15280?, 0x4?, 0x4?})
        /Users/zroubali/go/src/knative.dev/kn-plugin-func/cmd/deploy.go:69 +0x25
github.com/spf13/cobra.(*Command).execute(0xc0008b8a00, {0xc000b15240, 0x4, 0x4})
        /Users/zroubali/go/src/knative.dev/kn-plugin-func/vendor/github.com/spf13/cobra/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000274000)
        /Users/zroubali/go/src/knative.dev/kn-plugin-func/vendor/github.com/spf13/cobra/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/zroubali/go/src/knative.dev/kn-plugin-func/vendor/github.com/spf13/cobra/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /Users/zroubali/go/src/knative.dev/kn-plugin-func/vendor/github.com/spf13/cobra/command.go:895
main.main()
        /Users/zroubali/go/src/knative.dev/kn-plugin-func/cmd/func/main.go:37 +0x232
```

**Comment by lkingland** [comment]
It looks like we can perhaps accomplish the goal of these pointers (omitting empty values from the `func.yaml`) without the need to use the pointers to values by instead relying on the `yaml` library's `omitempty` field annotatin functionality.
 
In particular, by adding the annotation to the `Git` attribute of a `Function` [here](https://github.com/knative-sandbox/kn-plugin-func/blob/main/function.go#L65), thusly:
```Go
	Git Git `yaml:"git,omitempty"`
```
And simply removing the pointers on the `Git` object's fields (they already have `omitempty`) [here](https://github.com/knative-sandbox/kn-plugin-func/blob/main/function_git.go#L11), thusly:
```Go
type Git struct {
	URL        string `yaml:"url,omitempty"`
	Revision   string `yaml:"revision,omitempty"`
	ContextDir string `yaml:"contextDir,omitempty"`
}
```
We _should_ be able to keep these fields from showing up in the func.yaml while simultaneously being Go-idiom-friendly and relying on those default values.

Of course, were we to need to differentate between `nil` and empty string, such as when signaling an "unset" via a datagram (or similar), nils are necessary, but I think in this case we may be safe just using the annotations, since this is straight serialization and not an update message 👍🏻

**Comment by lkingland** [comment]
If #1075 is done correctly, it should also fix this issue.

**Comment by lkingland** [comment]
PR #1079 replaces the pointers which caused the acute issue here.  More generally, the command options were changed to be `--remote`, `--build` and `--git-url`.  The case which caused the error above is encapsulated by the test `TestDeploy_RemoteBuildURLPermutations` in `cmd/deploy_test.go` which now explicitly enumerates this and the other permutations.  For example, the cited use case above is now expressed:
```shell
func deploy --remote=false --git-url=example.com/myfunc.git
```
which results in an error as being currently unsupported
```Go
        // TODO: (enhancement) allow --git-url when running local deployment.
        // Check that the local builder is invoked with a directive to use a
        // git repo rather than the local filesystem if building is enabled and
        // a url is provided.  For now it throws an error statign that git-url
        // is only used when --remote
        if url != "" && err == nil {
          t.Fatal("error expected when deploying from local but provided --git-url")
          return
        } else if url != "" && err != nil {
          return // test successfully confirmed this is an error case
        }
```
Therefore, when #1079 lands, this should be resolved
