### ISSUE TITLE
Need better instructions for integrating plugin with kn cli

### ISSUE THREAD

**Issue by trisberg** [knative/func#903]
The docs in [integration-with-kn](https://github.com/knative-sandbox/kn-plugin-func/blob/main/docs/installing_cli.md#integration-with-kn) only point to the kn CLI docs that state that any plugin must have a `kn-` prefix. Curious why the `func` plugin doesn't conform to this out-of-the-box. I had to rename it to `kn-func` to get picked up as a `kn` plugin. This should at least be documented more clearly to help new users.

**Comment by lance** [comment]
@trisberg the install document has changed a bit over the last few months. Can you please take a look and close this issue if it resolves your concerns? The document now includes a few different ways to install, including `brew install func` and direct download. The need to name a binary `kn-func` is no longer there.

**Comment by trisberg** [comment]
Looks like I still need to rename when using a direct binary download

**Comment by lance** [comment]
Well, you need to rename if you want to use it as a `kn` plugin, and don't have access to `brew`. But you can also just use it as `func` standalone. We don't intend to change the name of the binary for downloads, afaik. This is similar to how `kn` itself works. The downloaded binaries from github are named according to architecture.

https://github.com/knative/client/releases/tag/knative-v1.5.0

**Comment by lance** [comment]
This should be resolved in https://github.com/knative/docs/pull/5243
