### ISSUE TITLE
Review and update spring cloud functions dependency for CVE

### ISSUE THREAD

**Issue by salaboy** [knative/func#929]
- Reference: https://spring.io/blog/2022/03/29/cve-report-published-for-spring-cloud-function

**Comment by lance** [comment]
The dependency that is used by the templates is `spring-cloud-dependencies` version 2021.0.1. This is an umbrella dependency that just pulls in a bunch of other dependencies. Reading [this blog post](https://www.dynatrace.com/news/blog/what-is-spring4shell-vulnerabilities-in-the-java-spring-framework/) about the issue, we are affected by “Information Exposure in Spring Cloud Function”, with a mitigation by a bump to `spring-cloud-functions` to 2.3.2 or higher. It appears to me that `spring-cloud-dependencies` has already made that bump based on my reading of this. https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-dependencies/2021.0.1

If this is all true, then I think we are good and function users should not be affected. I would like for someone with more recent Java experience to validate these findings, however, as it’s been years and my Java fu is rusty. 

/cc @trisberg
